### ISSUE TITLE
[Streams] Twitch Channels Names Getting Lowercased

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Red-DiscordBot#3655] opened 2020-03-14 06:21 UTC
# Command bugs

#### Command name
`streamalert`

#### What cog is this command from?
Streams

#### What were you expecting to happen?
When I use `streamalert twitch CoinTossTV` I expect the alert to use that case sensitive and not have the alert use all lowercase, like "cointosstv is live!"
For some reason sometime last year (IIRC) there was an update that changed this. Before you could add a channel as above and it would use the exact same input in the alert, for the channel, "CoinTossTV is live!"

#### What actually happened?
It changes the channel's name to all lowercase.

#### How can we reproduce this issue?
Add a Twitch channel that has both uppercase and lowercase letters and check the live alert.

**Comment by Jackenmen** [comment] 2020-03-14 18:20
I sadly can't reproduce this, Streams cog should use whatever casing the actual Twitch channel uses for its display name, for example twitch channel under url `twitch.tv/jackenmen` has `Jackenmen` as its display name as can be seen here: 
![image](https://user-images.githubusercontent.com/6032823/76687720-e5e4f800-6626-11ea-89c7-3670aaa9870a.png)

And even though I set stream alert using lower-case name, it shows the display name properly:
![image](https://user-images.githubusercontent.com/6032823/76687735-15940000-6627-11ea-911e-88c1586774bc.png)
![image](https://user-images.githubusercontent.com/6032823/76687770-5db32280-6627-11ea-8c1e-67790d0a9e86.png)

I don't really know what could be the reason of this happening, maybe try removing and adding stream alert again?

**Comment by Menteroth** [comment] 2020-03-14 18:22
My bad. I forgot I was using the 3.1.8 instance. I just tried with the 3.2.2 instance. It works fine.

**Comment by Jackenmen** [comment] 2020-03-14 18:24
Thanks for the update, I'm closing this issue then.

**Closed as completed by Jackenmen** 2020-03-14 18:24 UTC
Labels: Type: Bug, Closed: Invalid, Category: Cogs - Streams
