### ISSUE TITLE
Co-owner notifications not working 100% correctly.

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#3169] opened 2019-12-04 23:21 UTC
# Other bugs

#### What were you trying to do?

Using the bot (using systemd) with two discord UIDs passed via the co-owner flag. And have all owner's receive owner notifications and a message whenever `[p]contact` is used.

#### What were you expecting to happen?

When `-contact` gets used, all 3 "owner's" should have gotten a DM.

#### What actually happened?

Only the "main" owner got a DM.

#### How can we reproduce this issue?

Good question. This seems to randomly work at some times and not at others. Try using a bot with multiple co-owners triggerring `[p]contact` multiple Times and maybe give it a few restarts in between. I really don't know what causes this issue.

### Comment

I'm not sure if this is something that will even be looked at for fixing as the co-owner feature isn't supported at least in the support server. I verified that the problem exists using two seperate installs of red. Both did the same thing, I just couldn't find a regularity and am not sure how one could reproduce this without just having the bot run on a public server for a while.

**Comment by Flame442** [comment] 2019-12-04 23:25
The bot will post to console if sending the message fails in any way. The next time you have this issue, please check logs for an exception message. If there isn't anything in console when this happens, then there's probably an issue with the send_to_owners func, but I don't want to rule out something like one of the owners disabling the privacy option that allows server members to DM them.

Edit: mobile github why...

**Comment by Dav-Git** [comment] 2019-12-04 23:28
Setup on the owner's end is all fine. None have the bot blocked)unable to send DMs. I'll check the logs next time I notice it. The traceback command at least doesn't return any errors. Will check the actual log file the next time and keep this issue updated.

**Comment by Flame442** [comment] 2019-12-04 23:34
It would not show up in the traceback command, it is only silently logged.

Does it tend to stay working / not working until the bot is restarted or does it work sometimes and not work other times even without restarting?

**Comment by mikeshardmind** [comment] 2019-12-04 23:35
I can't reproduce this issue, have any of your cooowners opted out of recieving notifications and forgotten about this?

**Comment by Dav-Git** [comment] 2019-12-04 23:44
All of my co-owners are opted in. I made sure to check with all of them. 

On the working/not working: It depends. Sometimes it just works again after a while,sometimes it doesn't work until I restart and sometimes the restart doesn't even help.

**Comment by Dav-Git** [comment] 2019-12-04 23:48
If you can't reproduce/find anything in the code feel free to close this issue. I'll open another one when I have logs that can help.

**Comment by Dav-Git** [comment] 2019-12-06 18:29
So, the same has happened again. I went through every log I could find and all I got was that my lavalink exited early. Soo no luck on this front.

**Comment by Dav-Git** [comment] 2019-12-06 18:44
![grafik](https://user-images.githubusercontent.com/57032623/70347320-968d6f80-1860-11ea-8238-a24838c1cc3f.png)

I censored my server IP. The message should have been sent to all owners at 18:35.

**Comment by fixator10** [comment] 2019-12-07 07:26
> The message should have been sent to all owners at 18:35.

*Please, keep in mind, that journalctl shows time not in your local timezone, but in UTC (GMT) timezone.*

**Comment by Dav-Git** [comment] 2019-12-07 07:32
16:35 then. Still no log for whatever reason.

**Comment by mikeshardmind** [comment] 2020-01-04 04:54
Still haven't been able to reproduce this in any way which didn't get logged.

**Comment by mikeshardmind** [comment] 2020-01-08 16:19
I believe this should be working correctly in 3.2 based on other changes which have been made, I'm tenatively closing this, but if you still experience this after the release, please let us know.

**Closed as completed by mikeshardmind** 2020-01-08 16:19 UTC
Labels: Type: Bug, Status: Needs Info

**Comment by Dav-Git** [comment] 2020-01-08 18:49
Sounds good to me. I'll try again when 3.2 releases and keep you updated if necessary
