### ISSUE TITLE
Audio Track Playback Issue

### ISSUE THREAD

**Issue by MaddiFurr** [Cog-Creators/Red-DiscordBot#5819] opened 2022-08-12 01:57 UTC
The music side of RED was working just fine, then all of a sudden, audio will not play back. I think the upstream Lavalink server needs to be updated.

2022-08-12 01:20:26.950  INFO 146 --- [XNIO-1 I/O-16] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "[REDACTED]"}
2022-08-12 01:32:15.440  INFO 146 --- [XNIO-1 I/O-16] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "[REDACTED]", "track": "QAAAhgIAIUljZSBQb3NlaWRvbiAtIEN4IHNvbmcgKFJldXBsb2FkKQALWW91bmdKaWxrZXIAAAAAAASMEAALVzM5LWdyX1VQN2cAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1XMzktZ3JfVVA3ZwAHeW91dHViZQAAAAAAAAAA", "noReplace": false, "startTime": "0", "pause": false}
2022-08-12 01:32:16.412 ERROR 146 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of W39-gr_UP7g

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
    at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98-devoxin
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-41-generic
  java.vendor: Debian
  java.version: 11.0.15
  java.runtime.version: 11.0.15+10-post-Debian-1deb11u1
  java.vm.version: 11.0.15+10-post-Debian-1deb11u1
Caused by: java.lang.IllegalStateException: No match found
    at java.base/java.util.regex.Matcher.group(Matcher.java:645) ~[na:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:243) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:160) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:197) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:46) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:34) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[walkyst-lavaplayer-85f4877.jar!/:na]
    ... 4 common frames omitted

**Comment by aikaterna** [comment] 2022-08-12 01:59
Thanks, we are aware and have a Lavalink.jar prepped but there are other PRs to address first.

**Comment by MaddiFurr** [comment] 2022-08-12 02:01
Sounds good. Will wait for a fix to be pushed. Appreciate the swift response.

**Comment by aikaterna** [comment] 2022-08-12 02:03
I just noticed we're on the Red-Lavalink repo and not the Red-DiscordBot repo so I'm going to move this issue over there as this library is not affected and it's the audio backend side of things that is broken at the moment.

**Comment by MaddiFurr** [comment] 2022-08-12 02:10
Yeah, I put it there since it seemed to be an issue with Lavalink directly. No worries.

**Comment by aikaterna** [comment] 2022-08-12 21:56
PR's tied to this issue/needed for updating:

* #5821 
* #5822 
* @jack1142 , I can't find your PR that "reverts" #5751 to change the startup line detection to your ready check, that would go in this slot as needing to be included
* https://github.com/Cog-Creators/Red-Lavalink/pull/129

**Comment by ArchemedIan** [comment] 2022-08-14 05:46
quick fix: 

`export RedBotAudioCogLocation=***/you/should/probably/change/this/***~/.local/share/Red-DiscordBot/data/RedBot/cogs/Audio/ && cp $RedBotAudioCogLocation/Lavalink{.jar,.jar.old} && wget -O$RedBotAudioCogLocation/Lavalink.jar https://github.com/Cog-Creators/Lavalink-Jars/releases/download/3.4.0_1350/Lavalink.jar `

**Comment by ArchemedIan** [comment] 2022-08-14 15:45
how was that off topic at all?

**Comment by Drapersniper** [comment] 2022-08-14 16:05
By adding a comment that provided an unsupported fix that will break a lot of current users if they try to do what you suggested.

Leave the fixes and workaround for the people who are aware of the wider user base and repercussions for a given approach.

**Comment by ArchemedIan** [comment] 2022-08-14 16:29
what? name a SINGLE repercussion?  all the rest of the pr's are waiting on this jar, you telling me your code cant handle a file being replaced, when its literally going to replace that file? sorry, i may have a new github account, but i am by no means a noob, and i have four bs detectors attached to my head; my eyes and ears. i even added a command to keep the old jar, in case your code checksummed it for some reason, if you're checking the file creation date of a jar you're replacing or some crap, i concede, your dumb code will cause problems with this jar being replaced.

> people who are aware of the wider user base and repercussions for a given approach.

are these people aware their audio cog hasn't been working for days lmao.

**Comment by Kowlin** [comment] 2022-08-14 16:41
Please refrain from acting like this in our issues. If you want to go ahead and fix this for your self by the path you suggested that's fine with us. However this fix doesn't roll for us for an general production environment. We have an open PR (#5823) ready for this that we're planning on handling today.

> sorry, i may have a new github account, but i am by no means a noob, and i have four bs detectors attached to my head; my eyes and ears.

We do not filter content based on GitHub account age, experience or the amount of sensory elements one has. We do however filter based on our audience, the end user. If we feel like the fix suggested here may proof dangerous or harmful, as seen above, we will take action on it.

>  if you're checking the file creation date of a jar you're replacing or some crap, i concede, your dumb code will cause problems with this jar being replaced.

Now I'll be honest, I may not know our "dumb code" like some of our other contributors such as Draper here, but I fully entrust them that its working as intended. And that the above fix you've provided will not be compatible with it.

> are these people aware their audio cog hasn't been working for days lmao, that not a repercussion?

Yes, we are aware that we've received comments from people that Audio isn't working on an daily basis, and I'd like to remind you that there is an human on the other side of the argument here. We all have our own jobs to do, and our own live to life. Red for us isn't what brings in the money to pay the bills. It's an open source software project that we do in our spare time for fun.

I'm sorry that you think that our handling of your fix isn't the right thing to do. But I'm gonna stand with my team here and uphold it.

Have a wonderful rest of your day.

**Comment by Jackenmen** [comment] 2022-08-15 12:00
This has been fixed in Red 3.4.18.

**Closed as completed by Jackenmen** 2022-08-15 12:00 UTC
Labels: Type: Bug, Status: In Progress, Type: Dependency Update, Category: Cogs - Audio
