### ISSUE TITLE
Permissions YAML validation incorrect feedback

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#6239] opened 2023-08-22 22:06 UTC
Running `[p]permissions acl setserver` (or `setglobal`) with the valid YAML data below causes the message `Your YAML file did not match the schema: Top-level keys must be either COG or COMMAND.` to appear.

```yaml
COMMAND:
    addrole:
        55555555555:
```

The error is the fact that the snowflake does not have an explicit `true`/`false` value associated with it, so it is implicitly `null`. The same error happens if the snowflake is explicitly `null`, or is any other non-boolean value.

The logic for validating raw YAML inputs seems to not be selecting the correct error message for what is actually wrong with the schema.
https://github.com/Cog-Creators/Red-DiscordBot/blob/bb2e3687fc5151cce265632960a11addf02c1b26/redbot/cogs/permissions/permissions.py#L39-L76

**Comment by Jackenmen** [comment] 2023-08-22 22:22
Duplicate of #3185, feel free to comment with your example there but the issue comes down to the same thing.

**Closed as not planned by Jackenmen** 2023-08-22 22:22 UTC
Labels: Type: Bug, Status: PRs Welcome, Category: Cogs - Permissions
