### ISSUE TITLE
[V3 help] Issue with fuzzy help in DM

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#2069] opened 2018-08-30 07:50 UTC
# Command bugs

#### Command name

help

#### What cog is this command from?

No category

#### What were you expecting to happen?

Show a message with suggestions for commands.

#### What actually happened?

```py
Exception in command 'help'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/help_formatter.py", line 334, in help
    fuzzy_result = await fuzzy_command_search(ctx, name)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/utils/__init__.py", line 75, in fuzzy_command_search
    is_alias, alias = await alias_cog.is_alias(ctx.guild, term)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/alias/alias.py", line 60, in is_alias
    server_aliases = await self.unloaded_aliases(guild)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/alias/alias.py", line 41, in unloaded_aliases
    return (AliasEntry.from_json(d) for d in (await self._aliases.guild(guild).entries()))
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/config.py", line 782, in guild
    return self._get_base_group(self.GUILD, guild.id)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 896, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 533, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 70, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

#### How can we reproduce this issue?

*In DM*

- `!set fuzzy`
- `!help not_a_command`

**Comment by Tobotimus** [comment] 2018-09-02 10:17
Duplicate of #2031, I'm currently working on a fix for this on a local branch

**Closed as completed by Tobotimus** 2018-09-02 10:17 UTC
Labels: Closed: Duplicate
