### ISSUE TITLE
[V3 Downloader] cog list lists too much

### ISSUE THREAD

**Issue by bobloy** [Cog-Creators/Red-DiscordBot#1594] opened 2018-05-04 13:27 UTC
# Command bugs

#### Command name

`cog list`

#### What cog is this command from?

Downloader 

#### What were you expecting to happen?

List available cogs from provided Repo

#### What actually happened?

Lists many duplicates, more for larger cogs
![image](https://user-images.githubusercontent.com/955640/39630434-4c795c04-4f7d-11e8-9d1d-566e39a6ca91.png)

#### How can we reproduce this issue?

`[p]repo add Fox-V3 https://github.com/bobloy/Fox-V3`
`[p]cog list Fox-V3`

**Comment by TheWyn** [comment] 2018-05-04 14:29
Can confirm (Two pingtimes and three eventmakers):

![capture](https://user-images.githubusercontent.com/841141/39633405-e5b4948a-4f85-11e8-9970-d17578b33683.PNG)

**Comment by mikeshardmind** [comment] 2018-05-04 19:32
Seems to show an entry for each `.py` in a cog. But only seems to happen to installed cogs in a repo. (same issue here)

**Comment by tekulvw** [comment] 2018-05-23 00:22
I can't reproduce, someone's gonna have to sit in chat with me and help me debug this. Ping me on discord when any of you are available.

**Comment by tekulvw** [comment] 2018-05-23 00:37
Fixed with #1693

**Closed as completed by tekulvw** 2018-05-23 00:37 UTC
