### ISSUE TITLE
Track Error - Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by stefanusade** [Cog-Creators/Red-DiscordBot#6389] opened 2024-06-17 13:52 UTC
### What Red version are you using?

3.5.9

### Cog name

Audio

### Command name

play

### What did you expect to happen?

Bot playing song

### What actually happened?

Track error: Sign in to confirm you’re not a bot
![image](https://github.com/Cog-Creators/Red-DiscordBot/assets/85295874/9345d52b-d7a9-4aa3-b178-cc755eec5c4e)

### How can we reproduce this error?

1.
2.
3.
...

**Comment by BenCos17** [comment] 2024-06-17 15:05
known issue 
#4505 covers it

**Comment by Kowlin** [comment] 2024-06-18 02:26
Duplicate of #4505.

**Closed as not planned by Kowlin** 2024-06-18 02:26 UTC
Labels: Type: Bug, Status: Needs Triage
