### ISSUE TITLE
Some core commands stop working if you try to load audio after textmanipulator log was loaded

### ISSUE THREAD

**Issue by sravan1946** [Cog-Creators/Red-DiscordBot#4924] opened 2021-03-28 20:50 UTC
### What Red version are you using?

3.4.7

### What were you trying to do?

i was trying to load the audio cog but it gave error because the a command named remove was already existing from the textmanipulator cog

### What did you expect to happen?

the audio cog to load without any problem

### What actually happened?

when i did [p]load audio. it said This package could not be loaded for the following reason:

audio: Command remove is already an existing command or alias in one of the loaded cogs.

so i tryed to unload a few cogs and when i try to load the audio cog again, it does not respond

### How can we reproduce this error?

1.install the textmanipulator cog and load it
2.try to load the audio cog and it should say the command remove is already using by another cog
3.after that some of the core commands such as [p]load, [p]info stops working
...

Edit from @jack1142:
Permalink to the cog as it will most likely have the `[p]remove` command renamed:
https://github.com/Kreusada/Kreusada-Cogs/tree/9ac04440e4ff183da09602d5d7441c74f4749010/textmanipulator
(the issue is still something on Red's core side, I have no idea what yet though)

**Comment by Jackenmen** [comment] 2021-03-28 21:40
It is likely that this is somehow related to our (or d.py's) clean up that's done when cog fails to load but I don't want to rule out that it's something that Audio is doing.
The command appears to be removed from the bot's commands so it is NOT related to command checks.

**Comment by Jackenmen** [comment] 2021-03-28 22:36
This is caused by our dependency and has been fixed in here:
https://github.com/Rapptz/discord.py/commit/4aee7fed5df45eb2285b9677e5dd6eb3e2b140c1

I'm gonna leave this open until d.py releases a version with a fix for this and we update our dependency version.

**Comment by Jackenmen** [comment] 2021-04-05 21:11
This will be fixed in Red 3.4.8.

**Closed as completed by Jackenmen** 2021-04-05 21:11 UTC
Labels: Type: Bug, Status: Accepted, Category: Cogs - Audio
