### ISSUE TITLE
Track Error This video is not available

### ISSUE THREAD

**Issue by justintrotta** [Cog-Creators/Red-DiscordBot#6035] opened 2023-04-19 18:40 UTC
### What Red version are you using?

3.4.18

### Cog name

Audio

### Command name

play

### What did you expect to happen?

Audio to play

### What actually happened?

```
Track Error
This video is not available
```
Happens seemingly at the roll of a dice, no error is thrown in the console window. if I run the same [p]play [youtube link/query] many times in a row, maybe 50% of them actually queue up, the remainder throw "Track Error."

![sdrfgsdfg](https://user-images.githubusercontent.com/88599498/233169167-f6d2676d-3850-4f11-849d-cbcfcc2b49ab.JPG)

### How can we reproduce this error?

1. Run Redbot 3.4.18
2. Load audio
3. [p]play [youtube link/query]
4. repeat step 3 until error is thrown

**Comment by Flame442** [comment] 2023-04-19 18:53
Duplicate of #6034. This will be fixed with the next release.

**Closed as completed by Flame442** 2023-04-19 18:53 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by jdkang** [comment] 2023-04-19 18:58
Also seeing this issue on `3.4.18` with bundled LavaLink.
