### ISSUE TITLE
Bot randomly stops audio output or doesn't start correctly

### ISSUE THREAD

**Issue by lernzettel42** [Cog-Creators/Red-DiscordBot#4010] opened 2020-06-23 17:05 UTC
# Other bugs

#### What were you trying to do?

Case 1: I try to hear music
Case 2: I try to start the bot

#### What were you expecting to happen?

Case 1: I expect that the bot plays the music without any problems
Case 2: I expect that the bot starts up correctly and I can play music

#### What actually happened?

Case 1: The bot randomly stops producing audio playback, apart from that the bot is shown alive. I get no errors in the console.
Case 2: The bot starts without an error, but when I try to play something nothing happens, the command !now shows a timer located at 00:00:00, but it isn't paused.
In both cases only restarting the bot helps.

#### How can we reproduce this issue?

Don't know, I can tell you the environment I use:

- Raspberry Pi 3 
- tmux session

**Comment by Drapersniper** [comment] 2020-06-23 17:07
For support queries please go to https://discord.gg/red.

**Comment by Drapersniper** [comment] 2020-06-23 17:09
Closing issue as unable to reproduce, for further support please visit the support discord server linked  previously.

**Closed as completed by Drapersniper** 2020-06-23 17:09 UTC
Labels: No Repro, Category: Cogs - Audio
