### ISSUE TITLE
[V3 Alias] New lines don't get passed to target command

### ISSUE THREAD

**Issue by Olaroll** [Cog-Creators/Red-DiscordBot#2704] opened 2019-05-18 22:41 UTC
# Command bugs

#### Command name
   [p]alias

#### What cog is this command from?
   alias

#### What were you expecting to happen?
   When using an alias, new lines get passed on to the target command.

#### What actually happened?
   It removes the new lines and passes multiple lines as a single line to the target command.

#### How can we reproduce this issue?
   Should be pretty self explanatory, but here's a screencap [dead link]
   Also, although I'm not sure if it matters, the bug occurred on my v3.1.1 bot

**Comment by mikeshardmind** [comment] 2019-05-19 05:01
I cannot seem to replicate this. Can you check if the output of `!alias show s` has multiple lines?

**Comment by fixator10** [comment] 2019-05-19 05:41
Replicable.

Alias seems to be removing line breaks from arguments for cmd
![IMG](https://Moeka.is-a-good-waifu.com/4vxu52V.png)

**Comment by mikeshardmind** [comment] 2019-05-19 05:44
And here's an example where if the new lines were being stripped, I'd have a syntax error. This does not appear to be an issue with alias
![image](https://user-images.githubusercontent.com/22035876/57978251-7044d700-79d7-11e9-815c-c7ea04b9870c.png)

**Comment by mikeshardmind** [comment] 2019-05-19 05:45
oh I may have read the issue wrong here. just aliasing the command itself. 1 moment, I'll look a bit more.

**Comment by goettner** [comment] 2020-11-19 01:13
I'm pretty sure that I've written a fix for this issue on my fork, but I want to add some corresponding tests to the suite. Does anyone have any thoughts on the best way this could be done? I'm new to this project.

**Comment by RheingoldRiver** [comment] 2020-12-03 03:18
Just adding that this issue comes up really frequently in the Puzzle & Dragons community discord, with two commands, the more recent one is harder to work around:

For example, one cog we use is this one: https://github.com/TsubakiBotPad/misc-cogs/tree/master/msgutils

We create an alias `^alias add ee editmsg <channelid>` and then call it with 

```
^ee <msgid> some custom text that
spans more than one line
```

We'd expect the bot to edit the custom text to:

```
some custom text that
spans more than one line
```

but instead the message text is edited to:

```
some custom text that spans more than one line
```

This behavior can be reproduced with any command though, just find one that takes a custom text block that can reasonably span multiple lines and create an alias for it, then call the command with the alias as shown.

**Closed as completed** 2024-01-09 00:34 UTC
Labels: Type: Bug, Status: Needs Discussion, Category: Cogs - Alias
