### ISSUE TITLE
[V3 Downloader] Repo's not showing up after restart

### ISSUE THREAD

**Issue by Brramble** [Cog-Creators/Red-DiscordBot#2012] opened 2018-08-13 10:59 UTC
# Other bugs

#### What were you trying to do?

When I add a repo through the command to my bot it goes into the RepoManager and in repos.json as it should.

#### What were you expecting to happen?

I was expecting it to go into the [p]repo list command which is does but temporarily until the bot restarts

#### What actually happened?

It only shows the repos I add on that restart so if I add 3 repo's and restart the bot they all disappear from [p]repo list. However their files are still in RepoManager and their details are still in Repo.json

#### How can we reproduce this issue?

For me to reproduce this issue I installed a fresh bot on a new machine, added a couple of repositories and then restarted the bot. I then ran [p]repo list and they were all gone from the list.

**Comment by Tobotimus** [comment] 2018-08-13 12:56
Probable duplicate of #1950? Either way we appreciate you coming to us with new info. Are any error tracebacks showing up in your console when you restart the bot?

Also, are you able to provide the URLs to the repos you added?

**Comment by Brramble** [comment] 2018-08-13 18:25
Hi, This is exactly like #1950. This happened again also with only your repo added.

**Comment by Tobotimus** [comment] 2018-08-14 04:43
Thanks, I'll investigate. Marking as a duplicate of #1950.

**Closed as completed by Tobotimus** 2018-08-14 04:43 UTC
Labels: Type: Bug, Closed: Duplicate
