### ISSUE TITLE
[V3 Downloader] Error on cog update

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1628] opened 2018-05-11 15:55 UTC
# Command bugs

#### Command name

`cog update`

#### What cog is this command from?

`Downloader` from core

#### What were you expecting to happen?

Update all installed repos

#### What actually happened?

The error below was raised.

#### How can we reproduce this issue?

Don't know. Works fine for me but not for Malarne, and many other users when I'm looking at #v3-support 

### Error

```Py
Exception in command 'cog update'
Traceback (most recent call last):
  File "/home/admin/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/redbot/cogs/downloader/downloader.py", line 328, in _cog_update
    installed_cogs = set(await self.installed_cogs())
  File "/usr/local/lib/python3.6/site-packages/redbot/cogs/downloader/downloader.py", line 78, in installed_cogs
    return tuple(Installable.from_json(v, self._repo_manager) for v in installed)
  File "/usr/local/lib/python3.6/site-packages/redbot/cogs/downloader/downloader.py", line 78, in <genexpr>
    return tuple(Installable.from_json(v, self._repo_manager) for v in installed)
  File "/usr/local/lib/python3.6/site-packages/redbot/cogs/downloader/installable.py", line 210, in from_json
    repo_name = data['repo_name']
KeyError: 'repo_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/venv/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/admin/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 927, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/home/admin/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/admin/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'repo_name'
```

**Comment by Bakersbakebread** [comment] 2018-05-11 17:32
Many:
_noun_
1. the majority of people.

How to reproduce?

**Comment by laggron42** [comment] 2018-05-11 17:38
I don't know, it happens for some users.

**Comment by palmtree5** [comment] 2018-05-11 19:23
I haven't seen this in my experience either

**Comment by Malarne** [comment] 2018-05-11 19:26
http://prntscr.com/jgpt7r running b13 and python 3.6.3 on ubuntu 17.10

**Comment by unseenmagik** [comment] 2018-05-11 19:27
Running `[p]cog update` i also have the below error

```[10/05/2018 11:47] ERROR events on_command_error 202: Exception in command 'cog update'
Traceback (most recent call last):
  File "/home/unseenmagik/MB3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/unseenmagik/MB3/lib/python3.5/site-packages/redbot/cogs/downloader/downloader.py", line 328, in _cog_update
    installed_cogs = set(await self.installed_cogs())
  File "/home/unseenmagik/MB3/lib/python3.5/site-packages/redbot/cogs/downloader/downloader.py", line 78, in installed_co
gs
    return tuple(Installable.from_json(v, self._repo_manager) for v in installed)
  File "/home/unseenmagik/MB3/lib/python3.5/site-packages/redbot/cogs/downloader/downloader.py", line 78, in <genexpr>
    return tuple(Installable.from_json(v, self._repo_manager) for v in installed)
  File "/home/unseenmagik/MB3/lib/python3.5/site-packages/redbot/cogs/downloader/installable.py", line 210, in from_json
    repo_name = data['repo_name']
KeyError: 'repo_name```

**Comment by mikeshardmind** [comment] 2018-05-11 19:56
Can not reproduce this. Need more details. I can't even find a possible way for that key to not exist.in the code paths in the downloader

**Comment by laggron42** [comment] 2018-05-11 20:00
Wyn also got this error. This is not because we don't know how to reproduce that this error should be ignored.
<img width="657" alt="capture d ecran 2018-05-11 a 21 59 00" src="https://user-images.githubusercontent.com/23153234/39944328-8c54c93c-5566-11e8-8e2f-b95f4b8fc977.png">

**Comment by mikeshardmind** [comment] 2018-05-11 20:07
@retke not saying it isnt an issue, but it isnt easily reproducable,so we need more info to track the root cause down more efficiently.

**Comment by laggron42** [comment] 2018-05-11 20:09
I already try exploring the source code to see if I could fix it myself, but I got lost. The line 76 from downloader.py is calling a Class and expecting a dict.

**Comment by tekulvw** [comment] 2018-05-11 21:05
So a while back the structure of the data that downloader stores got changed and would cause this issue if the json file wasn't erased. Try renaming the settings.json file and see if the error goes away, I'll need to check the code later to confirm that you have an old version.

**Comment by Malarne** [comment] 2018-05-11 21:15
renamed CogManager/settings.json and Downloader/settings.json reloaded downloader, issue still there, still investigating ...

**Comment by tekulvw** [comment] 2018-05-11 23:27
Make sure you restart the bot after renaming.

**Comment by Malarne** [comment] 2018-05-12 05:42
restarting made the error go away

**Comment by tekulvw** [comment] 2018-05-23 00:12
Closing this for now, it's got to do with an older downloader config version.

**Closed as completed by tekulvw** 2018-05-23 00:12 UTC
