### ISSUE TITLE
Mod and Warning cog documentations

### ISSUE THREAD

**Issue by JKohlman** [Cog-Creators/Red-DiscordBot#4925] opened 2021-03-28 21:23 UTC
### What component of Red (cog, command, API) would you like to see improvements on?

Docs

### Describe the enhancement you're suggesting.

There is no documentation on either the Mod cog or the Warnings cog, both of which would be very useful for people wanting to understand how to use Red. The Mod cog exists in Docs v2 but Warnings doesn't.

**Comment by Kreusada** [comment] 2021-03-28 21:24
See #4886 and #4920

**Comment by JKohlman** [comment] 2021-03-28 21:28
Thanks! Looks like it's currently being worked on but is still an existing issue (until the PR is merged). I searched the issues for these and there weren't any so I made this one.

EDIT: Oh, it was just closed. There were no issues for this in Category: Docs, sorry for being a duplicate of whatever it was

**Comment by Jackenmen** [comment] 2021-03-28 21:29
There is already an issue for tracking progress on the user guides as it's an ongoing process.
Closing as duplicate of #1734

**Closed as completed by Jackenmen** 2021-03-28 21:29 UTC
Labels: Closed: Duplicate
