### ISSUE TITLE
Setup with PostgreSQL error(s)

### ISSUE THREAD

**Issue by klaudiadottv** [Cog-Creators/Red-DiscordBot#3469] opened 2020-01-29 13:17 UTC
I tried to install a new redbot with postgresql and when i ran the "redbot <instance>" command that happened:

```
The main bot task didn't handle an exception and has crashed
Traceback (most recent call last):
  File "/root/.pyenv/versions/Indigo/lib/python3.8/site-packages/redbot/__main__.py", line 419, in red_exception_handler
    red_task.result()
  File "/root/.pyenv/versions/Indigo/lib/python3.8/site-packages/redbot/__main__.py", line 306, in run_bot
    await driver_cls.initialize(**data_manager.storage_details())
  File "/root/.pyenv/versions/Indigo/lib/python3.8/site-packages/redbot/core/drivers/postgres/postgres.py", line 50, in initialize
    await cls._pool.execute(fs.read())
  File "/root/.pyenv/versions/Indigo/lib/python3.8/site-packages/asyncpg/pool.py", line 518, in execute
    return await con.execute(query, *args, timeout=timeout)
  File "/root/.pyenv/versions/Indigo/lib/python3.8/site-packages/asyncpg/connection.py", line 272, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 316, in query
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "NOT"
Attempting to die as gracefully as possible...

```

**Comment by Jackenmen** [comment] 2020-03-14 19:06
Hi, sorry that it took so long to get any response - we weren't able to reproduce this. I know it's been over a month since the issue was created so it's not very likely that you're still experiencing this issue but if you do, you should see if you're running PostgreSQL 10+ as we don't support anything lower (speaking of that, it should probably be included in our documentation).

This issue will be closed in 7 days if there won't be any response as there were no other reports of this issue.

**Closed as completed** 2020-03-22 00:00 UTC
Labels: Type: Bug, No Repro, Status: Needs Info, Category: Core - API - Config
