### ISSUE TITLE
[V3 Admin] Announcer is failing, still relying on default channel

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1395] opened 2018-03-05 22:26 UTC
### Type:

- Bug

### Brief description of the problem
`[p]announce` is still relying on the default channel to make announcements when the announce channel isn't specifically set in a guild:
```py
Traceback (most recent call last):
  File "/home/tobyh/PycharmProjects/Red-DiscordBot/redbot/cogs/admin/announcer.py", line 60, in announcer
    channel = await self._get_announce_channel(g)
  File "/home/tobyh/PycharmProjects/Red-DiscordBot/redbot/cogs/admin/announcer.py", line 46, in _get_announce_channel
    channel = guild.default_channel
AttributeError: 'Guild' object has no attribute 'default_channel'
```

### Expected behavior
The bot should either:
 1. Not announce if the channel isn't set
 2. Get a default announce channel some other way

### Actual behavior
Above error

### Steps to reproduce

1. Have the bot in a guild with the announce channel un-set
2. [p]announce message

**Comment by tekulvw** [comment] 2018-03-05 22:38
See #1381 and probable duplicate of #1378

**Closed as completed** 2018-03-05 22:46 UTC
Labels: Type: Bug, Closed: Duplicate
