### ISSUE TITLE
Error while using Install Requirements [audio]

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#686] opened 2017-04-01 09:15 UTC
Hello Im trying to install the music function of RedBot.
But for some reason I get this error. I dont know what is wrong.

`Collecting pip (from -r requirements.txt (line 1))
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\download.py", line 571, in written_chunks
    for chunk in chunks:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\utils\ui.py", line 141, in iter
    self.next(n)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\_vendor\progress\__init__.py", line 73, in next
    self.update()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\_vendor\progress\bar.py", line 79, in update
    self.writeln(line)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\_vendor\progress\helpers.py", line 68, in writeln
    print(line, end='', file=self.file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\_vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\_vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\pip\_vendor\colorama\ansitowin32.py", line 175, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 87] The parameter is incorrect
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-
8'>
OSError: [WinError 87] The parameter is incorrect

An error occurred and the requirements setup might not be completed. Consult the
 docs.`

Maybe you guys can help me out?!

Thanks

**Comment by Zephyrkul** [comment] 2017-04-01 09:31
What's your OS? What version of Python are you using?
Usually that error is caused by using Python 3.6+ on Windows, which is currently unsupported there (one of the requirements doesn't play nice with 3.6). If that's the case, uninstall Python 3.6 and install Python 3.5+ (3.5.3 is recommended).

Also, for future reference (and faster responses), feel free to join the official Red Discord server, we have a dedicated support channel there: https://discord.gg/red

**Comment by ghost** [comment] 2017-04-01 09:33
Im running on Windows Server 2012.
And yea, I found it myself too, that 3.6 was to high, so I went back to 3.5 and now its working perfectly.

Thanks!

**Comment by Kowlin** [comment] 2017-04-02 12:38
Issue is resolved, closing.

**Closed as completed by Kowlin** 2017-04-02 12:38 UTC
