### ISSUE TITLE
updateandreload command

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#5153] opened 2021-06-22 16:30 UTC
### What component of Red (cog, command, API) would you like to see improvements on?

downloader cog

### Describe the enhancement you're suggesting.

I would like to be able to update and reload all cogs with a single action, without having to click for confirmation afterwards. This would be especially nice for large cogs with a lot of files that take 30s+ to update and I'm just waiting around to click a checkmark. I could instead tab back to something else and refocus later on.

**Comment by Jackenmen** [comment] 2021-06-28 02:10
Duplicate of #3539

**Closed as completed by Jackenmen** 2021-06-28 02:10 UTC
Labels: Closed: Duplicate, Type: Enhancement
