### ISSUE TITLE
[V3] Repo Addition Error

### ISSUE THREAD

**Issue by LordHighfixxer** [Cog-Creators/Red-DiscordBot#1097] opened 2017-11-13 23:24 UTC
### Type:
- [X ] Bug

### Brief description of the problem
When adding my repo (that has been branched for V3) I receive the following error
### Expected behavior
Repo adds successfully
### Actual behavior
Traceback:

Cloning into '/root/.local/share/Red-DiscordBot/cogs/RepoManager/repos/ozcogsv3'...
remote: Counting objects: 1018, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 1018 (delta 10), reused 0 (delta 0), pack-reused 994
Receiving objects: 100% (1018/1018), 1.51 MiB | 1.91 MiB/s, done.
Resolving deltas: 100% (440/440), done.
[13/11/2017 17:59] ERROR events on_command_error 159: Exception in command 'repo add'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/downloader.py", line 212, in _repo_add
    branch=branch
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 541, in add_repo
    await self._save_repos()
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 628, in _save_repos
    repo_json_info = {name: r.to_json() for name, r in self._repos.items()}
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 628, in <dictcomp>
    repo_json_info = {name: r.to_json() for name, r in self._repos.items()}
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 475, in to_json
    "folder_path": self.folder_path.relative_to(Path.cwd()).parts,
  File "/usr/lib/python3.5/pathlib.py", line 864, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/root/.local/share/Red-DiscordBot/cogs/RepoManager/repos/ozcogsv3' does not start with '/home/pi'
Cloning into '/root/.local/share/Red-DiscordBot/cogs/RepoManager/repos/myv3alpha'...
remote: Counting objects: 1018, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 1018 (delta 10), reused 0 (delta 0), pack-reused 994
Receiving objects: 100% (1018/1018), 1.51 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (440/440), done.
[13/11/2017 18:05] ERROR events on_command_error 159: Exception in command 'repo add'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/downloader.py", line 212, in _repo_add
    branch=branch
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 541, in add_repo
    await self._save_repos()
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 628, in _save_repos
    repo_json_info = {name: r.to_json() for name, r in self._repos.items()}
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 628, in <dictcomp>
    repo_json_info = {name: r.to_json() for name, r in self._repos.items()}
  File "/usr/local/lib/python3.5/dist-packages/redbot/cogs/downloader/repo_manager.py", line 475, in to_json
    "folder_path": self.folder_path.relative_to(Path.cwd()).parts,
  File "/usr/lib/python3.5/pathlib.py", line 864, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/root/.local/share/Red-DiscordBot/cogs/RepoManager/repos/myv3alpha' does not start with '/home/pi'

Discord Bot Response:  Error in command 'repo add'. Check your console or logs for details.

### Steps to reproduce

1. Issue command [p]repo add REPONAME http://url to main git listing just like V2.address {branch]

**Comment by palmtree5** [comment] 2017-11-13 23:38
Duplicate of #1094

**Closed as completed by palmtree5** 2017-11-13 23:38 UTC
Labels: Closed: Duplicate
