### ISSUE TITLE
[Permissions] Allow setting generic "guild_admin" or "guild_owner" options in addglobalrule

### ISSUE THREAD

**Issue by LGACode** [Cog-Creators/Red-DiscordBot#3498] opened 2020-02-04 04:49 UTC
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [X] Command
- [ ] API functionality

#### Describe your requested feature

Would like to be able to restrict a cog/command globally while allowing all guild admins/owners. This would be simpler than having to allow the command on a server-by-server basis.

![image](https://user-images.githubusercontent.com/6125912/73714633-b01b2e00-46ce-11ea-9df8-5887194579f4.png)

In the above example:
`[p]permissions setdefaultglobalrule deny "permissions canrun"`
`[p]permissions addglobalrule allow "permissions canrun" --guild_admin`

Running these two commands would restrict permissions from normal users while still allowing for guild admins regardless of the name of their Admin role.

**Comment by Drapersniper** [comment] 2020-02-04 08:07
Using the admin role would be the way to get this to work, also non optional argparser in a core command is a non ideal thing and it’s likely to get pushback.

Not to mention that is this basing on wether the role has the admin permissions ? Or something ? Because the bot can’t know what role is the admin role without explicit say so from the user, and I would be agaisnt making assumptions here, since this is restricting something based on a role the user should have to be explicit about what role gets permission to run it

**Comment by mikeshardmind** [comment] 2020-02-04 10:22
While this isn't a direct duplicate of #3087, that contains a design for a real way to handle this. The version proposed in this issue isn't going to happen. That one will once anyone puts the time into doing it.

You can also write your own permission hooks for custom behavior. It's intentionally set up to be extendable.

**Closed as completed by mikeshardmind** 2020-02-04 10:22 UTC
Labels: Type: Feature, Status: Needs Triage
