### ISSUE TITLE
[Streams] YouTube streamalert raising Bad Request

### ISSUE THREAD

**Issue by jonttm** [Cog-Creators/Red-DiscordBot#2466] opened 2019-02-18 02:13 UTC
#### What were you trying to do?

Set a stream alert for YouTube `[p]streamalert youtube UCyd39rbwnC9LwYLfM0nHoNQ`

#### What were you expecting to happen?

Nothing (the channel was offline).

#### What actually happened?

After about 10 minutes, the bot notified that the stream was online (without an embed):
@everyone Channel Name is now live!

I then tried to check the channel using `[p]youtube UCyd39rbwnC9LwYLfM0nHoNQ` and it gave an error:

> Exception in command 'youtube'
> Traceback (most recent call last):
>   File "/home/jttm/red/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "/home/jttm/red/lib/python3.7/site-packages/redbot/cogs/streams/streams.py", line 95, in youtube
>     await self.check_online(ctx, stream)
>   File "/home/jttm/red/lib/python3.7/site-packages/redbot/cogs/streams/streams.py", line 142, in check_online
>     await ctx.send(embed=embed)
>   File "/home/jttm/red/lib/python3.7/site-packages/redbot/core/commands/context.py", line 63, in send
>     return await super().send(content=content, **kwargs)
>   File "/home/jttm/red/lib/python3.7/site-packages/discord/abc.py", line 808, in send
>     channel.id, content, tts=tts, embed=embed, nonce=nonce
>   File "/home/jttm/red/lib/python3.7/site-packages/discord/http.py", line 227, in request
>     raise HTTPException(r, data)
> discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/jttm/red/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 912, in invoke
>     await ctx.command.invoke(ctx)
>   File "/home/jttm/red/lib/python3.7/site-packages/discord/ext/commands/core.py", line 639, in invoke
>     await injected(*ctx.args, **ctx.kwargs)
>   File "/home/jttm/red/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message

When trying to reload the streams cog, the stream alert is sent again.

I verified that I had set up the YouTube API key correctly and it still happened. 

#### How can we reproduce this issue?

1. Setup a brand new Google API Project
2. Enable YouTube Data API v3
3. Add API Key Credentials
4. Run `[p]streamset youtubekey <token>`
5. Run `[p]streamalert youtube UCyd39rbwnC9LwYLfM0nHoNQ`
6. Wait some time or reload streams cog

**Comment by Jackenmen** [comment] 2020-08-17 14:37
I can't reproduce this, is this still an issue? I'll be closing this issue in 7 days if nobody comments here that they still experience this issue.

**Closed as completed** 2020-08-17 14:39 UTC
Labels: Type: Bug, No Repro, Status: Needs Info, Category: Cogs - Streams
