### ISSUE TITLE
Ubuntu 16.04.2: Unable to play long videos from YouTube. "ERROR: unable to rename file"

### ISSUE THREAD

**Issue by americanhanko** [Cog-Creators/Red-DiscordBot#844] opened 2017-07-03 03:02 UTC
Frequently receive the following error when trying to play audio from long YouTube videos:

```
python3.5[27536]: ERROR: unable to rename file: [Errno 2] No such file or directory: 'data/audio/cache/BN7sLcDUdYk.part' -> 'data/audio/cache/BN7sLcDUdYk'
python3.5[27536]: data/audio/cache/BN7sLcDUdYk: No such file or directory
```

- Max length is set to 14400 seconds
- The issue is resolved by deleting the ~contents of the cache directory~ cache directory and its contents. 
- The Red-DiscordBot repository is up-to-date. 
- `youtube-dl/xenial,xenial 2016.02.22-1 all`
- Package list:
```
chardet (2.3.0)
command-not-found (0.3)
language-selector (0.1)
pip (9.0.1)
pycurl (7.43.0)
pygobject (3.20.0)
python-apt (1.1.0b1)
python-debian (0.1.27)
python-systemd (231)
requests (2.9.1)
setuptools (20.7.0)
six (1.10.0)
ssh-import-id (5.5)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
wheel (0.29.0)
```

Videos that have caused this issue recently:

- https://www.youtube.com/watch?v=pUYwmkpmwxQ&t=2s (2 hours)
- https://www.youtube.com/watch?v=m5q7JL03F-Y (1 hour 43 minutes)

**Comment by palmtree5** [comment] 2017-07-03 03:13
Can you also post the output of `df -h`? Just to check that it isn't a storage issue

**Comment by americanhanko** [comment] 2017-07-03 03:19
@palmtree5 Sure thing.
```
Filesystem                               Size  Used Avail Use% Mounted on
udev                                     792M     0  792M   0% /dev
tmpfs                                    163M   18M  145M  11% /run
/dev/mapper/apex35erhank--chef--vg-root  291G   15G  261G   6% /
tmpfs                                    812M     0  812M   0% /dev/shm
tmpfs                                    5.0M     0  5.0M   0% /run/lock
tmpfs                                    812M     0  812M   0% /sys/fs/cgroup
/dev/sda2                                473M  175M  274M  39% /boot
/dev/sda1                                511M  3.4M  508M   1% /boot/efi
tmpfs                                    163M     0  163M   0% /run/user/1000
```

**Comment by americanhanko** [comment] 2017-07-03 03:21
Filesystem                               Size  Used Avail Use% Mounted on
udev                                     792M     0  792M   0% /dev
tmpfs                                    163M   18M  145M  11% /run
/dev/mapper/apex35erhank--chef--vg-root  291G   15G  261G   6% /
tmpfs                                    812M     0  812M   0% /dev/shm
tmpfs                                    5.0M     0  5.0M   0% /run/lock
tmpfs                                    812M     0  812M   0% /sys/fs/cgroup
/dev/sda2                                473M  175M  274M  39% /boot
/dev/sda1                                511M  3.4M  508M   1% /boot/efi
tmpfs                                    163M     0  163M   0% /run/user/1000
``````

**Comment by palmtree5** [comment] 2017-07-03 03:33
Yeah, storage is not the issue then

**Comment by tekulvw** [comment] 2017-07-12 04:51
This is...an interesting error and by far one of the most useful bug reports we've gotten. To confirm, the issue is resolved when you delete your entire cache folder? What is your maxcache size set to? Does the issue reappear right away or does it take some time for it to come back?

Max cache size can be found using `!debug bot.get_cog('Audio').settings["MAX_CACHE"]` and the next time this occurs can you check your current cache size using `!cache size` please?

**Comment by americanhanko** [comment] 2017-07-15 19:51
@tekulvw Thanks for you reply.
`MAX_CACHE` appears to be `0`, which would mean there is no limit, correct?
<img width="531" alt="screenshot 2017-07-15 12 50 21" src="https://user-images.githubusercontent.com/8458267/28242288-4401b2a4-695c-11e7-83ac-9df07e9b7598.png">

Also, my bot's name is `blue-bot` because it's the second Red-DiscordBot on our server 😏

**Comment by palmtree5** [comment] 2017-07-15 20:01
Out of curiousity, what's the output of `[p]cache minimum`?

**Comment by americanhanko** [comment] 2017-07-15 20:18
@palmtree5 60mb
<img width="395" alt="screenshot 2017-07-15 13 19 26" src="https://user-images.githubusercontent.com/8458267/28242434-414d871e-6960-11e7-9aea-d5d8b9a8ad8e.png">

**Comment by americanhanko** [comment] 2017-07-15 20:24
Happened a few times today already after restarting Red. I ran `Update Red + requirements` prior to this as well.
```-- Logs begin at Sat 2017-07-15 12:24:56 PDT. --
Jul 15 13:04:04 blue-bot python3.5[2000]: -----------------
Jul 15 13:04:04 blue-bot python3.5[2000]: Use this url to bring your bot to a server:
Jul 15 13:04:05 blue-bot python3.5[2000]: https://discordapp.com/oauth2/authorize?client_id=312814319991783424&scope=bot
Jul 15 13:04:05 blue-bot python3.5[2000]: Official server: https://discord.gg/red
Jul 15 13:04:05 blue-bot python3.5[2000]: Make sure to keep your bot updated. Select the 'Update' option from the launcher.
Jul 15 13:06:24 blue-bot python3.5[2000]: ERROR: unable to rename file: [Errno 2] No such file or directory: 'data/audio/cache/Gsdo4ol5bOk.part' -> 'data/audio/cache/Gsdo4ol5bOk'
Jul 15 13:06:24 blue-bot python3.5[2000]: ERROR: unable to download video data: [Errno 2] No such file or directory: 'data/audio/cache/Gsdo4ol5bOk'
Jul 15 13:06:29 blue-bot python3.5[2000]: data/audio/cache/Gsdo4ol5bOk: No such file or directory
Jul 15 13:10:05 blue-bot python3.5[2000]: ERROR: unable to rename file: [Errno 2] No such file or directory: 'data/audio/cache/PAWy4oXpuak.part' -> 'data/audio/cache/PAWy4oXpuak'
Jul 15 13:10:05 blue-bot python3.5[2000]: data/audio/cache/PAWy4oXpuak: No such file or directory
Jul 15 13:22:29 blue-bot python3.5[2000]: ERROR: unable to rename file: [Errno 2] No such file or directory: 'data/audio/cache/Gsdo4ol5bOk.part' -> 'data/audio/cache/Gsdo4ol5bOk'
Jul 15 13:22:29 blue-bot python3.5[2000]: ERROR: unable to download video data: [Errno 2] No such file or directory: 'data/audio/cache/Gsdo4ol5bOk'
Jul 15 13:22:40 blue-bot python3.5[2000]: data/audio/cache/Gsdo4ol5bOk: No such file or directory
```

**Comment by palmtree5** [comment] 2017-07-15 20:27
hmm, just had a thought. can you post the output of `ls -l data/audio/`?

**Comment by americanhanko** [comment] 2017-07-15 20:31
```
audio [develop %=] $ pwd
/home/eric/Red-DiscordBot/data/audio
audio [develop %=] $ ls -AFhlt
total 20K
-rw-r--r-- 1 eric eric  409 Jul 15 13:27 settings.json
drwxr-xr-x 2 eric eric 4.0K Jul 15 13:22 cache/
drwxr-xr-x 3 eric eric 4.0K Jul  1 12:52 playlists/
drwxr-xr-x 2 eric eric 4.0K Jun  1 20:59 localtracks/
drwxr-xr-x 2 eric eric 4.0K Jun  1 20:59 sfx/

**Comment by palmtree5** [comment] 2017-07-15 20:34
Hmm, ok. The bot has write access to the cache dir so that's not the issue

**Comment by tekulvw** [comment] 2017-07-15 21:03
So the issue here is that your cache size is 60mb. The cache cleaner will go through about every minute and if your cache is currently larger than the limit it will delete all files that aren't currently being played (and those that are next to be played). I never thought of the partial download files and so the cleaner is deleting them as the bot is trying to download them. For now you can increase your max cache size as a temporary fix by using `!audioset cachemax`

**Comment by tekulvw** [comment] 2017-07-15 21:10
And so you're aware, zero is not equivalent to no limit, the cache size is determined by the maximum of "cache minimum" and whatever you've set your cachemax to.

As an aside, yes the way audio handles cached files is a bit wonky.and will be fixed in V3 but we'll be making no significant effort to modify it in it's current state.

**Comment by americanhanko** [comment] 2017-07-15 22:43
Ah, I see it now.
```python
def _cache_max(self):
    setting_max = self.settings["MAX_CACHE"]
    return max([setting_max, self._cache_min()])  # enforcing hard limit

def _cache_min(self):
    x = self._server_count()
    return max([60, 48 * math.log(x) * x**0.3])  # log is not log10
```

So, the user experience for this is interesting.
I can run `?cache minimum` to **get** my *minimum* cache size...
and I can run `?audioset maxcache` to **set** my *maximum* cache size.
But I can't do the reverse for either?

Maybe add something like:

```python
@cache.command(name="maximum")
async def cache_maximum(self):
    """Current max cache size.  User setting or minimum, whichever is higher"""
    await self.bot.say("The max cache is set to {:.3f} MB".format(self._cache_max()))
```

**Comment by tekulvw** [comment] 2017-07-18 17:50
You're not allowed to set cache minimum size because it needs to be a reasonable number (e.g. not zero). The lack of a `cache maximum` command is an oversight and should be PR'd. One of us will likely get around to that soon.

Can I confirm that the issue is resolved for now?

**Comment by americanhanko** [comment] 2017-07-18 18:23
Yes. I've submitted PR https://github.com/Twentysix26/Red-DiscordBot/pull/861 for the `!cache maximum` command and some other very minute changes.

**Closed as completed** 2017-07-18 18:23 UTC
