### ISSUE TITLE
[Streams] Allow only certain games to announce

### ISSUE THREAD

**Issue by EternalllZM** [Cog-Creators/Red-DiscordBot#4990] opened 2021-04-14 23:41 UTC
### What component of Red (cog, command, API) would you like to see improvements on?

Command/API

### Describe the enhancement you're suggesting.

When working around a community that is specific to a certain game or community, there is a preference that people only wish to watch Twitch streams from a certain game.

Currently, every single stream no matter what game is announced and unable to be automatically filtered out. 

It would be nice to have a command such as:
**[p]streamset games whitelist <<game>>**

**Comment by Jackenmen** [comment] 2021-06-28 01:36
Duplicate of #2356

**Closed as completed by Jackenmen** 2021-06-28 01:36 UTC
Labels: Closed: Duplicate, Type: Enhancement
