### ISSUE TITLE
[Core] set game isn't working if game ommited. 

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#3641] opened 2020-03-06 22:57 UTC
# Command bug

#### Command name

`[p]set game`

#### What cog is this command from?

`Core`

#### What were you expecting to happen?

I was expecting the bot to clear the bot's status. 

#### What actually happened?

```
Exception in command 'set game'
Traceback (most recent call last):
  File "/home/ubuntu/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/red/lib/python3.8/site-packages/redbot/core/core_commands.py", line 1082, in _game
    if len(game) > 128:
TypeError: object of type 'NoneType' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/red/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/red/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/home/ubuntu/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/ubuntu/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object of type 'NoneType' has no len()
```

#### How can we reproduce this issue?

- Use `[p]set game` without indicating a status.

**Comment by Jackenmen** [comment] 2020-03-06 22:59
Duplicate of #3628, the mentioned issue has already been closed and the fix will be included in next release.

**Closed as completed by Jackenmen** 2020-03-06 22:59 UTC
Labels: Type: Bug, Closed: Duplicate

**Comment by madebylydia** [comment] 2020-03-06 23:01
Didn't saw, sorry.

**Comment by Jackenmen** [comment] 2020-03-06 23:03
@Predeactor no problem, thank you for reporting a potential issue anyway :)
