### ISSUE TITLE
when running [p]help if [p]helpset usemenus, the reactions from user aren't auto-deleted when page is turned

### ISSUE THREAD

**Issue by leElvyn** [Cog-Creators/Red-DiscordBot#4076] opened 2020-07-15 18:01 UTC
# Command bugs

#### Command name

[p]help

#### What cog is this command from?
core

#### What were you expecting to happen?

the user reactions are auto-deleted when changing pages

#### What actually happened?

user reactions aren't deleted, you have to manually remove and re-click to change pages

#### How can we reproduce this issue?
turn on [p]helpset usemenus and use [p]help

**Comment by yamikaitou** [comment] 2020-07-15 18:04
Does your bot have the Manage Reactions permission? I can't reproduce this

**Comment by Jackenmen** [comment] 2020-07-15 18:05
Please also send output of `[p]cogs` and `[p]debuginfo` commands

**Comment by Drapersniper** [comment] 2020-07-16 17:02
No need here this is the designed behaviour.

The current red menus only accept the signal when adding reactions.

In the future this will not be the case, also removing the user reaction on every reaction would:
1. Required manage message permissions
2. A lot of api calls.

So it will never happen, however when #4062 is merged you will be able to use both Adding a reaction and Removing a reaction as button signals to the menu.

**Closed as completed by Drapersniper** 2020-07-16 17:02 UTC
Labels: Type: Bug, Closed: User Error

**Comment by Drapersniper** [comment] 2020-07-16 20:09
Welp ... so turns out I'm very wrong here...
The menu will remove the reactions if the bot has manage manages in that channel, and and this has been the case since 05/04/2018.
