### ISSUE TITLE
`[p]warn` Causes unexpected results when an apostrophe is in the warning message

### ISSUE THREAD

**Issue by TrustyJAID** [Cog-Creators/Red-DiscordBot#5762] opened 2022-06-06 19:04 UTC
### What Red version are you using?

3.4.16

### Cog name

Warnings

### Command name

warn

### What did you expect to happen?

The warning to proceed as usual.

### What actually happened?

Help is sent instead for the command.

### How can we reproduce this error?

1. enable custom warning messages
2. `[p]warn @user can't do something`

### Anything else?

After some investigating, the `UserInputOptional` does not provide the expected default and treats the missing input as `None` instead of the default `1` in the command signature. This leads to the bot not knowing what to do and sends the help message instead. If the first word of the warning message does not contain an apostrophe it works as expected and provides the default of `1`.

**Comment by Jackenmen** [comment] 2022-06-06 23:29
I'm unable to reproduce this, am I missing something (custom reasons are enabled)?
![image](https://user-images.githubusercontent.com/6032823/172265501-c9e67f69-0b93-418b-9cac-b7f29819f6a6.png)

`UserInputOptional` at runtime means the same exact thing as [`Optional` does for d.py](https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#typing-optional) so this should work fine unless there's a bug somewhere in discord.py 1.7.3.

**Comment by TrustyJAID** [comment] 2022-06-06 23:32
Huh it would appear my example does not affect it but `[p]warn @user don't believe you` does, it's inconsistent when and where it works.

**Comment by Jackenmen** [comment] 2022-06-07 00:21
The issue on d.py 1.7.3 is caused by Rapptz/discord.py#7386 - in such a case a parsing error is raised and the command isn't even executed. On d.py 2.0 this issue was fixed however the Optional's default wasn't applied properly but this has since been fixed by Rapptz/discord.py#8119. I'm going to close this as it's going to be resolved once we bump our d.py version and there is nothing else to do on our side in relation to this issue.

**Closed as completed by Jackenmen** 2022-06-07 00:21 UTC
Labels: Type: Bug, Status: Needs Triage
