### ISSUE TITLE
Music - Youtube - googlevideo.com domain

### ISSUE THREAD

**Issue by vacances** [Cog-Creators/Red-DiscordBot#6156] opened 2023-05-13 18:46 UTC
### What Red version are you using?

Docker latest

### What were you trying to do?

Play youtube music via the bot.

### What did you expect to happen?

Bot should join and play youtube music.

### What actually happened?

Bot is joining and music will not start, I'm getting an error below:
```
Track Error
Something broke when playing the track.
```

Logs are showing that the cause of that is googlevideo.com:

`Caused by: java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to rr2---sn-oxup5-3ufz.googlevideo.com:443 [rr2---sn-oxup5-3ufz.googlevideo.com/0.0.0.0] failed: Connection refused (Connection refused)`

I host my own DNS server that is blocking disgusting telemetry and ads, but the youtube and all of the webpages are working correctly on every device at home (including youtube, even on devices like TizenTV without adblocker). Did something change in the code? Last successful attempt registered was on 1.03.2023. I realized that it was broken around mid-03.2023. Since then i'm using a public bot because i don't really want to resolve that domain if everything else is working as intended. I didn't change anything in my internal DNS or bot settings.
Should i just stop using it for good?
Soundcloud was working fine, i tested it just in case.

### How can we reproduce this error?

On every attempt (PREFIX)play.

**Comment by Flame442** [comment] 2023-05-13 19:15
You didn't include a clear version in your report. The version can be checked with the command `[p]info`, or by running `redbot --version` in your venv. If you are running a version prior to 3.4.19, you are using an outdated version of lavalink that is known to have issues.

That being said, these issues could also be caused by running on docker. Docker is not a supported operating system to run Red on, so you may need to take any issues you have with it to the author of the image you are currently using. Our docs include a [list of supported operating systems with installation guides](https://docs.discord.red/en/stable/install_guides/index.html) and [a list of common available hosting providers](https://docs.discord.red/en/stable/host-list.html).

I was not able to reproduce this issue on a supported OS, so I am going to assume your issue is related to one of the two issues I mentioned above and close it.

**Closed as not planned by Flame442** 2023-05-13 19:15 UTC
Labels: Closed: Invalid
