### ISSUE TITLE
Ability to enable the bot to @mention roles or @everyone through customcom and other cogs

### ISSUE THREAD

**Issue by HeliumYang** [Cog-Creators/Red-DiscordBot#4547] opened 2020-10-27 13:42 UTC
# Feature request

#### Select the type of feature you are requesting:

- [x] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature
Prior to the 3.4.0 update, I used to use customcoms and other exterior cogs to ping roles. I understand that some bot users may not like this, so rather than bringing it back for everyone, the bot could potentially have an admin command that enables pinging roles or everyone. This can be set to false by default, and the bot command can be [p]pingrole true/false

**Comment by Jackenmen** [comment] 2020-10-27 13:47
CustomCommands have never allowed to ping roles. This looks to me as a duplicate of #2518.
As for 3rd-party cogs, it's up to a cog to decide whether it should allow making mass mentions.

**Closed as not planned by Jackenmen** 2020-10-27 13:47 UTC
Labels: Closed: Duplicate
