### ISSUE TITLE
[Blacklist] Adding unknown user through ID errors

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#3563] opened 2020-02-17 12:23 UTC
# Command bugs

#### Command name

blacklist add

#### What cog is this command from?

Core

#### What were you expecting to happen?

Error for cannot find user or add user to blacklist 

#### What actually happened?

Threw an exception about int object having no .id attribute 

#### How can we reproduce this issue?

Attempt to add a user using id who is not currently in the server
![Screenshot_20200217-122041](https://user-images.githubusercontent.com/31554168/74653502-31b79500-5180-11ea-9d55-f4788834f763.jpg)

**Comment by Stonedestroyer** [comment] 2020-02-17 12:26
Should be resolved by #3472 that's in dev branch.

**Comment by Jackenmen** [comment] 2020-02-17 12:30
As Slime said, this had already been fixed in dev. Closing as a duplicate of #3220.

**Closed as completed** 2020-02-17 12:30 UTC
Labels: Type: Bug, Closed: Duplicate
