### ISSUE TITLE
[V3] Downloader repo issue

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#1564] opened 2018-04-23 17:53 UTC
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
I can not add repos under the same name when I delete them.
### Expected behavior
I should be able to add the same repo back to the same name I deleted it from, I tried to restart as well.
### Actual behavior
The bot replies with 
```That git repo has already been added under another name.```. 
https://i.imgur.com/szClNp7.png
It works to add under different name but I can not reuse the same name.
### Steps to reproduce

1. Add a repo like this
[p]repo add jumperplugins https://github.com/Redjumpman/Jumper-Plugins V3
2. 
Remove the repo
3. 
Try to add the repo again to same name.
4. 
Using different names work. Rebooting does not help.

**Comment by palmtree5** [comment] 2018-04-30 00:35
I cannot reproduce this with the above reproduction steps

EDIT: My bot's on Linux (specifically, Ubuntu 18.04). Seems like this is Windows-related

**Comment by Stonedestroyer** [comment] 2018-04-30 01:04
Okay so the major issue seems to be that it does not delete the folder in repomanager/repos. Deleting test1 folder and readding repository works.

**Comment by tekulvw** [comment] 2018-05-17 20:22
Fixed with #1578

**Closed as completed by tekulvw** 2018-05-17 20:22 UTC
