### ISSUE TITLE
[mongodb] Error This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#3061] opened 2019-10-15 19:45 UTC
# Other bugs

#### What were you trying to do?

Update bot

#### What were you expecting to happen?

Nothing.

#### What actually happened?

```Traceback (most recent call last):
  File "f:\eban\lib\site-packages\pymongo\mongo_client.py", line 1385, in _retry_with_session
    return func(session, sock_info, retryable)
  File "f:\eban\lib\site-packages\pymongo\collection.py", line 1161, in _delete
    retryable_write=retryable_write)
  File "f:\eban\lib\site-packages\pymongo\collection.py", line 1147, in _delete
    retryable_write=retryable_write)
  File "f:\eban\lib\site-packages\pymongo\pool.py", line 613, in command
    user_fields=user_fields)
  File "f:\eban\lib\site-packages\pymongo\network.py", line 167, in command
    parse_write_concern_error=parse_write_concern_error)
  File "f:\eban\lib\site-packages\pymongo\helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Transaction numbers are only allowed on a replica set member or mongos

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\eban\lib\site-packages\redbot\core\drivers\mongo.py", line 226, in set
    await mongo_collection.delete_many(pkey_filter, session=session)
  File "f:\python\Lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "f:\eban\lib\site-packages\pymongo\collection.py", line 1240, in delete_many
    collation=collation, session=session),
  File "f:\eban\lib\site-packages\pymongo\collection.py", line 1165, in _delete_retryable
    _delete, session)
  File "f:\eban\lib\site-packages\pymongo\mongo_client.py", line 1492, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "f:\eban\lib\site-packages\pymongo\mongo_client.py", line 1426, in _retry_with_session
    raise OperationFailure(errmsg, exc.code, exc.details)
pymongo.errors.OperationFailure: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\python\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\python\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "f:\eban\lib\site-packages\redbot\__main__.py", line 182, in <module>
    main()
  File "f:\eban\lib\site-packages\redbot\__main__.py", line 118, in main
    loop.run_until_complete(red._maybe_update_config())
  File "f:\python\Lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "f:\eban\lib\site-packages\redbot\core\bot.py", line 336, in _maybe_update_config
    await self._schema_1_to_2()
  File "f:\eban\lib\site-packages\redbot\core\bot.py", line 350, in _schema_1_to_2
    basically_bulk_update.update(token_mapping)
  File "f:\eban\lib\site-packages\redbot\core\config.py", line 88, in __aexit__
    await self.value_obj.set(self.raw_value)
  File "f:\eban\lib\site-packages\redbot\core\config.py", line 534, in set
    await super().set(value)
  File "f:\eban\lib\site-packages\redbot\core\config.py", line 230, in set
    await self.driver.set(self.identifier_data, value=value)
  File "f:\eban\lib\site-packages\redbot\core\drivers\mongo.py", line 275, in set
    (pymongo.InsertOne(d) for d in to_insert if d),
  File "f:\eban\lib\site-packages\redbot\core\drivers\mongo.py", line 275, in <genexpr>
    (pymongo.InsertOne(d) for d in to_insert if d),
  File "f:\eban\lib\site-packages\redbot\core\drivers\mongo.py", line 304, in generate_documents_to_insert
    document["_id"] = {"RED_uuid": uuid, "RED_primary_key": primary_keys + [pkey]}
TypeError: 'str' object does not support item assignment```

#### How can we reproduce this issue?

help me

**Comment by Jackenmen** [comment] 2019-10-15 19:46
Looks related to #3020

**Comment by mikeshardmind** [comment] 2019-10-18 23:46
Closing this, [duplicate of] root issue in #3020

**Closed as completed by mikeshardmind** 2019-10-18 23:46 UTC
