### ISSUE TITLE
Config defaults not actually updating after a cog reload

### ISSUE THREAD

**Issue by i-am-zaidali** [Cog-Creators/Red-DiscordBot#5805] opened 2022-07-25 16:13 UTC
### What Red version are you using?

3.4.16

### What were you trying to do?

Updating guild defaults for Config in my cog.

### What did you expect to happen?

For the new defaults to be returned when `.all()` is called on a Group object. 

### What actually happened?

Old defaults being returned instead.

### How can we reproduce this error?

1. Create a cog and a config instance tied to the config with force registration set to True
2. Set guild defaults for the config objects.
3. Load the cog and modify the config values.
4. Change the defaults set to config by removing a few keys and adding a few.
5. Reload the cog and try running `.clear()` on a Group.

**Comment by Flame442** [comment] 2022-08-19 22:11
EDIT: Misread the report, see followup comment which actually addresses the real issue.

I believe this is intended behavior. Config **does not** have an option to **remove** defaults, only to **add** new defaults or to **override** current ones. As such, successive `register_scope` calls will **add** the provided keys (if they did not exist), and will **override** the current default (if they did exist) for each key. There is no way (I can see, through the public APIs) to **remove** a default once it has been set without creating a new Config object.

Through my testing, this behavior is correct:
When keys are **added**, they become functional, and have the new default (`baz` in the following example). 
When keys are **overridden**, a `clear` causes the new default to be used instead of the old one (`foo` in the following example).
When keys are **not included**, they are not "removed", they just do not get changed. The old default continues to be used (`bar` in the following example).

If you are seeing different behavior, please provide a code sample to reproduce the behavior you are describing, as your reproduction steps do not have any specific lines of code used beyond `.clear()`. If your issue matches with this intended behavior and you want to make a feature request to add a way to *remove* existing defaults during the life of a Config option, please make a new issue requesting that instead.

<details>
<summary>Code (Hidden, as it is not relevant to the actual bug report, see followup comment)</summary>
<br>
Code I used to attempt to reproduce your issue (this is code suited for a testing eval, not code that should be considered at all reasonable to use in production)

```py
from redbot.core.config import Config

async def printall():
  print("> Printing current values")
  print("foo=",await bot.x.guild(ctx.guild).foo())
  try:
    print("bar=",await bot.x.guild(ctx.guild).bar())
  except Exception as e:
    print("bar=",e)
  try:
    print("baz=",await bot.x.guild(ctx.guild).baz())
  except Exception as e:
    print("baz=",e)

bot.x = Config.get_conf("Testing", identifier=145519400223506432, cog_name="Testing", force_registration=True)
print("> Registering defaults foo=foo | bar=bar")
bot.x.register_guild(
  foo="foo",
  bar="bar",
)
await printall()
print("> Setting guild values foo=foofoo | bar=barbar | baz=bazbaz")
await bot.x.guild(ctx.guild).foo.set("foofoo")
await bot.x.guild(ctx.guild).bar.set("barbar")
try:
  await bot.x.guild(ctx.guild).baz.set("bazbaz")
except Exception as e:
  print("baz set: ", e)
await printall()
print("> Registering defaults foo=foofoofoo | baz=bazbazbaz")
bot.x.register_guild(
  foo="foofoofoo",
  baz="bazbazbaz",
)
await printall()
print("> Clearing guild values")
await bot.x.guild(ctx.guild).foo.clear()
try:
  await bot.x.guild(ctx.guild).bar.clear()
except Exception as e:
  print("bar clear: ", e)
await bot.x.guild(ctx.guild).baz.clear()
await printall()
```
Output
```
> Registering defaults foo=foo | bar=bar
> Printing current values
foo= foo
bar= bar
baz= 'baz' is not a valid registered Group or value.
> Setting guild values foo=foofoo | bar=barbar | baz=bazbaz
baz set:  'baz' is not a valid registered Group or value.
> Printing current values
foo= foofoo
bar= barbar
baz= 'baz' is not a valid registered Group or value.
> Registering defaults foo=foofoofoo | baz=bazbazbaz
> Printing current values
foo= foofoo
bar= barbar
baz= bazbazbaz
> Clearing guild values
> Printing current values
foo= foofoofoo
bar= bar
baz= bazbazbaz
```
</details>

**Comment by Flame442** [comment] 2022-08-19 22:22
So it looks like I missed the "reload" part of your original report - my bad. Updated code snippet below, which includes a simulated "reload", showing that creating a *new* Config object properly clears defaults (when used correctly).

The behavior is still consistent with what it should be in *this* case as well:
When keys are **added**, they become functional, and have the new default (baz in the following example).
When keys are **overridden**, a clear causes the new default to be used instead of the old one (foo in the following example).
When keys are **not included**, the default is "removed", but **internally** the current value (NOT the default) does not get changed If that key is registered later, it will **still have the old value**. However, attempting to get the value after clearing *while it has not been registered for the current Config object* will either raise an exception if `force_registration=True`, or will return the base default of `None` (bar in the following example).

Again, if this behavior is not what you expect for any reason, feel free to comment with a code snippet and an explanation of what you believe should be happening.

```py
from redbot.core.config import Config

async def printall():
  print("> Printing current values")
  print("foo=",await bot.x.guild(ctx.guild).foo())
  try:
    print("bar=",await bot.x.guild(ctx.guild).bar())
  except Exception as e:
    print("bar=",e)
  try:
    print("baz=",await bot.x.guild(ctx.guild).baz())
  except Exception as e:
    print("baz=",e)

print("> Creating Config object")
bot.x = Config.get_conf("Testing", identifier=145519400223506432, cog_name="Testing", force_registration=True)
print("> Registering defaults foo=foo | bar=bar")
bot.x.register_guild(
  foo="foo",
  bar="bar",
)
await printall()
print("> Setting guild values foo=foofoo | bar=barbar | baz=bazbaz")
await bot.x.guild(ctx.guild).foo.set("foofoo")
await bot.x.guild(ctx.guild).bar.set("barbar")
try:
  await bot.x.guild(ctx.guild).baz.set("bazbaz")
except Exception as e:
  print("baz set: ", e)
await printall()
print("> Recreating Config object")
del bot.x
bot.x = Config.get_conf("Testing", identifier=145519400223506432, cog_name="Testing", force_registration=True)
print("> Registering defaults foo=foofoofoo | baz=bazbazbaz")
bot.x.register_guild(
  foo="foofoofoo",
  baz="bazbazbaz",
)
await printall()
print("> Clearing guild values")
await bot.x.guild(ctx.guild).foo.clear()
try:
  await bot.x.guild(ctx.guild).bar.clear()
except Exception as e:
  print("bar clear: ", e)
await bot.x.guild(ctx.guild).baz.clear()
await printall()
```
Output
```
> Creating Config object
> Registering defaults foo=foo | bar=bar
> Printing current values
foo= foo
bar= bar
baz= 'baz' is not a valid registered Group or value.
> Setting guild values foo=foofoo | bar=barbar | baz=bazbaz
baz set:  'baz' is not a valid registered Group or value.
> Printing current values
foo= foofoo
bar= barbar
baz= 'baz' is not a valid registered Group or value.
> Recreating Config object
> Registering defaults foo=foofoofoo | baz=bazbazbaz
> Printing current values
foo= foofoo
bar= 'bar' is not a valid registered Group or value.
baz= bazbazbaz
> Clearing guild values
bar clear:  'bar' is not a valid registered Group or value.
> Printing current values
foo= foofoofoo
bar= 'bar' is not a valid registered Group or value.
baz= bazbazbaz
```

**Comment by Flame442** [comment] 2022-11-09 06:13
Due to not receiving a response, and this seeming like intended behavior, I'm closing this issue. If you still think there is an issue, and you can provide exact reproduction steps similar to what I wrote, I can take another look at this.

**Closed as not planned by Flame442** 2022-11-09 06:13 UTC
Labels: Type: Bug, No Repro, Status: Needs Info
