### ISSUE TITLE
[Filter] `[p]filter` does not warn when DMs are blocked

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3924] opened 2020-06-05 21:08 UTC
not too familiar with the cog.
but would assume the following in the reason it doesn't list anything.

```py
commands.group(name="filter")
    @commands.guild_only()
    @checks.mod_or_permissions(manage_messages=True)
    async def _filter(self, ctx: commands.Context):
        """Add or remove words from server filter.

        Use double quotes to add or remove sentences.

        Using this command with no subcommands will send the list of
        the server's filtered words.
        """
        if ctx.invoked_subcommand is None:
```

**Comment by Drapersniper** [comment] 2020-06-05 21:17
Welp no im dumb

**Comment by Flame442** [comment] 2020-06-05 21:17
Filter listing is currently in DMs with no warning if the bot is blocked, that should probably be added anyway. Opening this issue until that is fixed.

**Comment by Flame442** [comment] 2020-06-05 21:33
The issue is actually a completely unrelated thing, I'm going to make a PR to fix it now and it is out of the scope of this issue, so I am closing it.

**Closed as completed by Flame442** 2020-06-05 21:33 UTC
Labels: Type: Bug, Status: Needs Triage
