### ISSUE TITLE
[Audio] Local tracks with special characters in path wont return a value in all cases

### ISSUE THREAD

**Issue by ltukezl** [Cog-Creators/Red-DiscordBot#3467] opened 2020-01-28 13:56 UTC
# Command bugs

#### Command name

[p]local folder
[p]local play

#### What cog is this command from?
audio

#### What were you expecting to happen?

trying to play a folder with spaces in path such as:
https://puu.sh/F4B4A/9070d830aa.png
and selecting 2

should result in playing all songs inside that folder

#### What actually happened?
Nothing found message.
http://puu.sh/F4B5s/45eb04af34.png

#### How can we reproduce this issue?

make (symlink) folder. add another folder inside it with a space in name. "redbot test" and try to play it.

**Comment by Drapersniper** [comment] 2020-01-30 09:32
Blocked by #3459

**Comment by Drapersniper** [comment] 2020-02-08 11:26
@ltukezl  I'm unable to reproduce this any longer ...

![image](https://user-images.githubusercontent.com/27962761/74084308-c37b2000-4a65-11ea-81cd-675161d58c3c.png)
![image](https://user-images.githubusercontent.com/27962761/74084312-cc6bf180-4a65-11ea-828c-d6fb7fc1265d.png)

Is this still an issue for you if it is please post the output of `[p]audioset settings` and `[p]debuginfo`

**Comment by ltukezl** [comment] 2020-02-08 12:29
Folders with only spaces do work now.
folders with "[]" doesn't work for example "tst 1 [tst]" still gives "Nothing found". maybe other special markings too but didn't test others.

----Server Settings----        
Auto-disconnect:  [Disabled]
Auto-play:        [Disabled]
Repeat:           [Disabled]
Shuffle:          [Disabled]
Shuffle bumped:   [Enabled]
Song notify msgs: [Disabled]
Songs as status:  [Disabled]

---Cache Settings---        
Max age:          [365 days]
Spotify cache:    [Disabled]
Youtube cache:    [Disabled]
Lavalink cache:   [Disabled]

---Lavalink Settings---        
Cog version:      [1.1.1]
Red-Lavalink:     [0.4.2]
External server:  [Disabled]
Localtracks path: [E:\red-musicbot\cogs\Audio]

Red version
3.3.1
Python version
3.8.1 (64bit)
Discord.py version
1.3.1
Pip version
20.0.2
System arch
AMD64
OS version
Windows 10 (version 10.0.17134)
Python executable
c:\python38\python.exe

**Comment by Drapersniper** [comment] 2020-02-08 14:42
Will be fixed as part of the next Audio update

**Comment by Drapersniper** [comment] 2020-02-29 17:28
This has been fixed in the feature branch

**Closed as completed** 2020-05-20 20:30 UTC
Labels: Type: Bug, Status: In Progress, Category: Cogs - Audio
