### ISSUE TITLE
[V3-Mongodb, Economy] - Payday Error

### ISSUE THREAD

**Issue by Kio-td** [Cog-Creators/Red-DiscordBot#1569] opened 2018-04-26 21:03 UTC
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
When Users attempt to claim for payday, users get an error instead of the payment.
The same error happens when starting up, too.
### Expected behavior
Responds with You collected [x] Tn..
### Actual behavior
```[26/04/2018 16:57] ERROR events on_command_error 198: Exception in command 'payday'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/economy/economy.py", line 247, in payday
    pos = await bank.get_leaderboard_position(author)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/bank.py", line 354, in get_leaderboard_position
    leaderboard = await get_leaderboard(None, guild)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/bank.py", line 312, in get_leaderboard
    raw_accounts = await _conf.all_users()
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/config.py", line 928, in all_users
    return await self._all_from_scope(self.USER)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/config.py", line 854, in _all_from_scope
    dict_ = await group()
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/config.py", line 76, in _get
    ret = await self.driver.get(*self.identifiers)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/drivers/red_mongo.py", line 82, in get
    projection={dot_identifiers: True}
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 1225, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python3.6/dist-packages/pymongo/cursor.py", line 1169, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.6/dist-packages/pymongo/cursor.py", line 1085, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/cursor.py", line 971, in __send_message
    codec_options=self.__codec_options)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/cursor.py", line 1055, in _unpack_response
    return response.unpack_response(cursor_id, codec_options)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/message.py", line 945, in unpack_response
    return bson.decode_all(self.documents, codec_options)
bson.errors.InvalidBSON: 'utf-8' codec can't decode byte 0xed in position 1: invalid continuation byte
```
### Steps to reproduce
Unfourtanatly, I do not know how to reproduce this error.

**Comment by Kio-td** [comment] 2018-04-26 21:45
Edit: It occured to me and a friend of mine that users still receive the money, and that the leader board command is also affected by this error.

**Comment by tekulvw** [comment] 2018-05-17 20:21
Does this happen for all users or just a few?

**Comment by Kio-td** [comment] 2018-05-18 14:27
Looks like all of my users get this error, but are able to claim.

**Comment by pgaetani** [comment] 2018-05-22 10:59
There's an invalid UTF8 string somewhere in the document Mongo is trying to access. Perhaps the config driver's get/set funcs need to specify encoding?

**Comment by tekulvw** [comment] 2018-06-06 19:09
Are you still having this issue?

**Comment by tekulvw** [comment] 2018-06-07 05:18
So I've done some research and it looks like your bson document in mongo somehow managed to get mangled. I'm not sure how this is possible and can't reproduce it. This issue would *not* be caused by weird characters in usernames so I'm going to close this for now until we see it again or can get some more information.

**Closed as completed by tekulvw** 2018-06-07 05:18 UTC
Labels: Type: Bug
