### ISSUE TITLE
Ghost playlists on an instance restored from a backup

### ISSUE THREAD

**Issue by Kirass0** [Cog-Creators/Red-DiscordBot#5134] opened 2021-06-12 22:36 UTC
### What Red version are you using?

3.4.11

### What were you trying to do?

I was creating a clone of my bot using backup procedure. It was on 5th March, so I was using Red version from that time.

### What did you expect to happen?

All my data working and usable on a second instance.

### What actually happened?

All my Global playlist are not listed under "playlist list" command, but are still preset somehow. I can use "playlist info" on them or even play them. Trying to delete them doesn't throw any errors, but their state doesn't change.

### How can we reproduce this error?

1. Have an instance with some Global playlists.
2. Create a backup and start a new instance using that backup.
3. Check if Global playlist behave like described above.

~~I didn't try to reproduce it, so maybe there was another factor in my case.~~
I did a new backup and the same thing happend. All global playlist are invisible on a new instance.

### Anything else?

My discord name is Kirass#5074 if you want to ask something.

**Comment by Flame442** [comment] 2022-08-19 18:45
I cannot reproduce this issue on 3.4.18 with the following steps:
1. Create a global playlist with `[p]playlist create GlobalPlaylist --scope global`
2. Add a few songs to the playlist with `[p]playlist append GlobalPlaylist a search term`
3. Stop the bot
4. Run `redbot-setup backup <instancename>`
5. Extract the backup file somewhere else
6. Run redbot-setup to create a new instance with the extracted backup's folder as the datapath
7. Start the instance

At this point, `[p]playlist list` **does** show the playlist, `[p]playlist info` works as expected, and `[p]playlist delete` properly deletes the playlist, removing it from `list` and `info`. I'm not sure if this issue has been fixed since 3.4.11, or if you followed a different set of instructions to reproduce it. If you can still reproduce it on 3.4.18, please give **exact** reproduction steps (like I did above) as well as the output of `[p]debuginfo` on any instances involved in the process.

**Comment by Kowlin** [comment] 2022-10-18 19:48
Closing due to no reproduction.

**Closed as not planned by Kowlin** 2022-10-18 19:48 UTC
Labels: Type: Bug, No Repro, Status: Needs Info, Category: Cogs - Audio
