### ISSUE TITLE
Confusing help files for playing a local track

### ISSUE THREAD

**Issue by bugtrapper** [Cog-Creators/Red-DiscordBot#4777] opened 2021-01-31 12:29 UTC
# Other bugs

#### What were you trying to do?

I wanted to find out the command to play a local track.

#### What were you expecting to happen?

I expected to [p]help, [p]help local, [p]help play or [p]help local play to inform me about the correct command.

#### What actually happened?

[p]help local and [p]help local play make it look like [p]local play <parent folder>/track.mp3 would be the correct command. [p]help play doesn't include the information that this works for local files as well. It only mentions URLs, which are I understood to be links to the Internet, not inside Red's local folder (after all, a full file URL doesn't work, either).

#### How can we reproduce this issue?

Use the commands
[p]help
[p]help local
[p]help local play
[p]help play
and read the help given.

**Comment by Drapersniper** [comment] 2021-01-31 13:42
Sorry but I'm not entirely sure I follow, you said help local and help local play tells you how to play and help play doesn't tell you how to play... this appears to be the intended behaviour or am I missing something here ?

**Comment by bugtrapper** [comment] 2021-01-31 16:07
Sorry for the confusing bug report.
The **correct** command to directly play a local file is `[p]play <parentfolder>/file.mp3`.

`[p]help local` and `[p]help local play` suggest the command would be `[p]local play <parentfolder>/file.mp3`. This does not work. It is the wrong command. The help entries are confusing.

`[p]help play` suggests that it's only supposed for online files, not local files. It does not convey that it is the correct command to play local files, _although that is the case_. The help file is unclear / incomplete.

Consequently, I would like to suggest updating these entries accordingly.

**Comment by davidhu99** [comment] 2021-04-20 20:24
Hi! Can I be assigned this?

**Comment by aikaterna** [comment] 2021-04-20 20:59
This is already being worked on in https://github.com/Cog-Creators/Red-DiscordBot/pull/4832 as was linked above your comment.

**Closed as completed** 2021-05-18 22:09 UTC
Labels: Good First Issue, Status: In Progress, Type: Informational, Category: Cogs - Audio
