### ISSUE TITLE
The removal of !sfx and functionally to !queue? Curious.

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#287] opened 2016-06-01 23:58 UTC
Maybe it's my ineptness, but when I updated the bot, the sfx folder still exists but the !sfx command is no longer existent.

!queue also no longer displays the song queue, instead just has the bot leave a message about how to use the !queue command.

**Comment by ddday** [comment] 2016-06-02 00:05
The audio module has been recently re-written. The sfx command was removed but will likely come back as a 3rd party cog. 

As to queue I have no idea.

**Comment by tekulvw** [comment] 2016-06-02 01:54
Duplicate of #257 and sfx is gone in rewrite, look for a 3rd party cog in the future

**Closed as completed** 2016-06-02 01:55 UTC
