### ISSUE TITLE
data files not getting updated

### ISSUE THREAD

**Issue by DeltaSigma130** [Cog-Creators/Red-DiscordBot#856] opened 2017-07-11 18:14 UTC
When I commit new data files only with no .py changes and run `/cog update`, Red reports " No updates to apply.".  This forces me to do a `/cog uninstall` followed by a `/cog install` to get the new data files.

**Comment by tekulvw** [comment] 2017-07-11 18:18
Not an issue and won't fix as this is working as intended. Downloader checks the git **server** for updates only.

**Closed as completed by tekulvw** 2017-07-11 18:18 UTC
