### ISSUE TITLE
Provide Channel Option for Commands

### ISSUE THREAD

**Issue by V1perN3st** [Cog-Creators/Red-DiscordBot#5543] opened 2022-01-16 01:06 UTC
### Type of feature request

Cog

### Description of the feature you're suggesting

While messing with RedBot, I noticed that to setup Stream Alerts in the Stream module you need to put the command into the channel you want the alert to come up in. This causes a lot of extra work as we now need to delete each of the commands and the bot's responses to keep the channel clean. If we can provide the Channel ID as part of the command, then we can use one channel to do all of the configuration without having to delete messages from the different channels we need to specifically run the command in.

This can be applied to other commands that do similar functions, allowing Discord Admins to keep all of the bot spam within one channel (which could also be a configuration option within RedBot to limit where commands can be ran and/or where the bot responds) while being able to configure RedBot for their Discord and not have to delete messages and responses to "clean up" after the configuration is done (and any future configuration that might be added or removed).

**Comment by Jackenmen** [comment] 2022-01-16 01:12
Duplicate of #3866, will be fixed by #5160.

**Closed as completed by Jackenmen** 2022-01-16 01:12 UTC
Labels: Closed: Duplicate, Type: Feature
