### ISSUE TITLE
[V3 Config] config items defaulted with a list all share the same list until reloaded from file

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1294] opened 2018-02-08 23:14 UTC
It appears that name changes are logged ans saved to every user in the same guild. Error somewhere in ``on_member_update`` logic.

**Comment by Kowlin** [comment] 2018-02-08 23:41
Root of issue tracked down.
https://github.com/Cog-Creators/Red-DiscordBot/blob/194981cd8ba7543b1f653ab1266c08028041c34c/redbot/cogs/mod/mod.py#L1351

So far unknown on why it takes and saves it to all members in a shared guild. I'm thinking this is a config bug regarding using "User"

**Comment by palmtree5** [comment] 2018-02-09 05:22
I'm now seeing this with nicknames as well

**Comment by palmtree5** [comment] 2018-02-09 06:41
Actually, the issue with nicks (and selfroles) is something that seems to be different from the issue occurring here. Nicks and selfroles lead to the wrong result showing when doing `[p]eval` to show the value, but those aren't being written to disk. In the case of names, the names are being written to disk in more than just their intended destination

EDIT: test cases should probably be included relating to this (@Chovin)

**Comment by Chovin** [comment] 2018-02-09 07:58
For more detail:

### Behaviors observed:
1. Config structures using lists\* added using `config.register_member`\*\* when accessed via async context manager like so: `async with settings.member(member).some_list() as the_list:` all share the same list.
2. Lists pulled from disk are not effected, so if only one default member is added followed by a reload of the cog, the following default member will not share the same list as the previous (NOTE: There are irregularities)

### Steps to reproduce: 
 with persons named `A, B, C` having ids `1, 2, 3` respectively
1. Delete mod cog's settings json if exists and `[p]reload mod`
2. `A` change name to `sloop`
3. `[p]names A` gives Past 20 names: **sloop**
4. `[p]names B` gives Past 20 names: **sloop**
5. `
#!/eval print(await bot.get_cog("Mod").settings.member(guild.get_member(1)).past_names() is await bot.get_cog("Mod").settings.member(guild.get_member(2)).past_names())
` 
gives `True`
This exhibits behavior 1
compare with `#!/eval print([] is [])` gives `False`

6. `[p]reload mod`
7. `A` change name to `pools`
8. `[p]names A` gives Past 20 names: **sloop, pools**
9. `[p]names B` gives Past 20 names: **sloop**
This exhibits behavior 2
10. repeat steps 2-9 but with nicknames instead. you should notice that steps 6-9 give different results, `B` having no past nicknames. 
These are the irregularities observed in behavior 2

Further examples can be be seen in the conversation following the most recent pin 
(id `411390561174683649` at time of writing) in the `#advanced-testing` channel of our Discord

\* Behaviors may not effect dicts
\*\* Behavior is assumed to be the same for member/user/guild/channel, etc.

**Comment by Tobotimus** [comment] 2018-02-13 23:28
This issue is not exclusive to the async context manager, I was able to reproduce this issue using the normal get and set method.

**Comment by tekulvw** [comment] 2018-02-15 00:12
Fixed with #1308

**Closed as completed by tekulvw** 2018-02-15 00:12 UTC
Labels: Type: Bug
