### ISSUE TITLE
[V3] Warnings cog issue

### ISSUE THREAD

**Issue by evacfk** [Cog-Creators/Red-DiscordBot#2106] opened 2018-09-07 21:21 UTC
# Command bugs

#### Command name

.warn

#### What cog is this command from?

Warnings

#### What were you expecting to happen?

When a user goes above the points threshold, the assigned action should occur.

#### What actually happened?

User gets warned and points get added however no action is issued.

#### How can we reproduce this issue?

Create a warnreason, assign it a point value and set that point value to ban a user.
 Then warn the user.

Here's an example of what I have setup and the bot has done nothing to the user

http://evac.gg/i/pthl6.png

When setting up the action, i used:

ban {user}

**Comment by Jamesp1989SL** [comment] 2018-09-08 07:59
Seems to be an issue with the mod cog not the warning cog. Entering the command myself +ban someusername gives a hierarchy error even if i turn off that check with modset heiarchy

**Comment by mikeshardmind** [comment] 2018-09-08 08:38
@useruser3 Not related to the mod cog. I cannot reproduce the behavior you are describing.

I **also** cannot reproduce a lack of warning actions actually being triggered.

**Comment by Jamesp1989SL** [comment] 2018-09-08 10:51
@evacfk try restarting your bot. Resolved it for me

**Comment by evacfk** [comment] 2018-09-08 20:59
Did not resolve for me.

**Comment by eaten-squid** [comment] 2018-09-09 09:19
I'm able to reproduce this.

**Comment by evacfk** [comment] 2018-09-10 06:07
Updated to B21 and same issue exists. I've tried restarting bot, reloading warnings.

I don't see any errors, on bot startup I get 

"Unknown event GUILD_INTEGRATIONS_UPDATE."

But that's it.

**Comment by palmtree5** [comment] 2018-09-10 08:20
That message is a discord.py issue (see Rapptz/discord.py/issues/1083)

**Comment by elijabesu** [comment] 2018-09-26 16:00
I also have the problem with the warning and also with the hierarchy

Some more info to the problem:
I have two roles for my V3: `SauriBot` and `Owner's Baby Bots`, where the second one is there purely just so the bot appears below Verified members while the first role is all the way above everyone (and is the one with all permissions). I also have set that after 3 warnings (= 3 points), the user shall be kicked out and if rejoined, after another one (4 points in total), the user shall be banned from the server. This, however, does not happen, [as seen here](https://cdn.discordapp.com/attachments/387398816317440000/492025505369948162/cats.jpg). Also, the manual kick and ban with `[p]kick <user>` and `[p]ban <user>` give me an error whenever the user has higher role than `Owner's Baby Bots`, even tho it's below `SauriBot`, [as seen here](https://cdn.discordapp.com/attachments/387398816317440000/492025514064609280/cats2.jpg).

Those two basically go hand in hand together as the bot cannot kick the person, [as seen here](https://cdn.discordapp.com/attachments/483402230540533770/494545337290063872/unknown.png) (tried it right now with my second account).

**Comment by Tobotimus** [comment] 2018-10-11 21:19
Resolved by #2218.

**Closed as completed by Tobotimus** 2018-10-11 21:19 UTC
Labels: Type: Bug
