### ISSUE TITLE
[Audio] Document Lavalink setup with multiple instances

### ISSUE THREAD

**Issue by alfonsojon** [Cog-Creators/Red-DiscordBot#2843] opened 2019-07-08 03:00 UTC
# Other bugs

#### What were you trying to do?

Run two instances of Red on a server for two different Discord servers. After that, `!load audio`.

#### What were you expecting to happen?

Both servers should be able to play audio

#### What actually happened?

Whichever server starts first has the ability to play music. The server(s) that start afterward display this error:
```
[CRITICAL] red.audio.manager: Internal lavalink server exited early
[WARNING] red.audio.manager: Timeout occurred whilst waiting for internal Lavalink server to be ready
[INFO] red.audio.manager: Internal Lavalink jar shutdown unexpectedly
[INFO] red.audio.manager: Restarting internal Lavalink server
```

#### How can we reproduce this issue?

1. Install two instances of Red to two different folders.
2. `!load audio` on both servers
3. Attempt to play any audio on the second server. It will not work. 
4. Check console -- see errors listed above.

[image](https://user-images.githubusercontent.com/1163298/60780063-9434b700-a102-11e9-8373-f427c45ffb39.png)

**Comment by alfonsojon** [comment] 2019-07-08 03:02
Once the internal lavalink server restarts, it works fine; however, it's still an issue on launch.

**Comment by Flame442** [comment] 2019-07-08 03:04
This is intended behavior. Both bots try to use the lavalink server on the same port and fail. The fix is to use external lavalink `[p]llset external` on both bots and run lavalink separately (externally). For more help (and if you run in to any issues in the future), you can ask for help in the support channel of the red server (discord.gg/red).

**Comment by alfonsojon** [comment] 2019-07-08 03:11
@Flame442 Thank you very much! So just run lavalink standalone and point Red at the standalone server then?

**Comment by Flame442** [comment] 2019-07-08 03:14
Yep, pretty much. Run one lavalink for both bots to use and make sure both bots are set to use external lavalink. If you need any help setting it up, feel free to ask in the discord server.

**Comment by alfonsojon** [comment] 2019-07-08 03:31
Got it. Thanks! I'll join now.

**Comment by Tobotimus** [comment] 2019-07-08 03:31
We should document this. Leaving it open until that's done :)

**Comment by yamikaitou** [comment] 2019-07-08 03:46
Just to add, ?multibots in our discord gives basic instructions on what to do

**Comment by Drapersniper** [comment] 2020-06-04 08:46
Note: Do not work on this for the time being. Also is going through some major rework on the near future and the instructions here will fundamentally change.

**Comment by aikaterna** [comment] 2021-12-31 01:52
Linking this to https://github.com/Cog-Creators/Red-DiscordBot/pull/4872 as instructions for multiple bots will be included with the docs when they are complete.

**Closed as completed** 2022-10-31 01:43 UTC
Labels: Category: Docs - Other, Status: Accepted, Status: PRs Welcome, Category: Cogs - Audio
