### ISSUE TITLE
Issue with emoji reactions to menus in 3.5-dev

### ISSUE THREAD

**Issue by RheingoldRiver** [Cog-Creators/Red-DiscordBot#5906] opened 2022-11-16 03:39 UTC
### What Red version are you using?

3.5-dev starting with commit [f025283](https://github.com/Cog-Creators/Red-DiscordBot/commit/f02528378f0d71a7bb2de72348eae4e2718a4d38)

### What were you trying to do?

Add emojis to a menu, like this, in a specified order, with more emojis than the rate-limit

![image](https://user-images.githubusercontent.com/18037011/202076836-0b331d50-e99e-469d-b264-d5ca0b484d81.png)

### What did you expect to happen?

1. Always have the emojis print in the same order every time (we ensure that they're sent in the same order every time by our code)
2. Handle the rate-limit errors gracefully & retry as needed

### What actually happened?

Through commit [d7d6ab4](https://github.com/Cog-Creators/Red-DiscordBot/commit/d7d6ab46f45e7057a21df4f7f908fe6e5cf48523), this was handled fine. Starting with commit [f025283](https://github.com/Cog-Creators/Red-DiscordBot/commit/f02528378f0d71a7bb2de72348eae4e2718a4d38), however:

1. The emojis printed in a random order
2. Upon hitting the ratelimit, an error was printed to the user, and no retry happened

![image](https://user-images.githubusercontent.com/18037011/202077178-059fc817-c7c8-41e8-bc4d-d5786313d5d7.png)
![image](https://user-images.githubusercontent.com/18037011/202077239-cc0611c1-1782-4039-b63b-63d085e4e819.png)
![image](https://user-images.githubusercontent.com/18037011/202077275-3d390753-524c-4731-b143-656ee54e9ced.png)

### How can we reproduce this error?

1. Make a command that creates an embed and adds at least 6 emoji reactions, in the same order to it, it doesn't actually need to be a functioning menu. But [here are our cogs](https://github.com/TsubakiBotPad/pad-cogs) if you want to install them. You would need `dbcog` and `padinfo`, and it should work with just that, the command is `[p]id`.
2. Run the command with commit f025283 or later.

### Anything else?

We updated our bot a week ago, but the issue started today, so I'm not sure what's up with that. However, rolling back the Red version fixed the issue so there's definitely something going wrong that started with that commit. And it wasn't an ephemeral thing for just a few minutes either, it was broken for about 5 hours before we thought to try a rollback.

**Comment by Flame442** [comment] 2022-11-16 03:54
Seems like a duplicate of #5905, just with a different endpoint. Closing this in favor of that issue.

**Closed as completed by Flame442** 2022-11-16 03:54 UTC
Labels: Closed: Duplicate

**Comment by RheingoldRiver** [comment] 2022-11-16 04:28
```
Exception in command 'id'
Traceback (most recent call last):
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/bot/.local/share/Red-DiscordBot/data/tsubaki_prod/cogs/CogManager/cogs/padinfo/padinfo.py", line 219, in _id
    await self._do_id(ctx, query)
  File "/home/bot/.local/share/Red-DiscordBot/data/tsubaki_prod/cogs/CogManager/cogs/padinfo/padinfo.py", line 275, in _do_id
    await menu.create(ctx, state)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discordmenu/embed/menu.py", line 38, in create
    return await send_embed(ctx, embed_wrapper, message=message)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discordmenu/discord_client.py", line 54, in send_embed
    await asyncio.gather(*add)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/message.py", line 1061, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc

discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.
```
