### ISSUE TITLE
[Streams] Cog tries to access event loop after it was closed during shutdown.

### ISSUE THREAD

**Issue by Robert606** [Cog-Creators/Red-DiscordBot#3881] opened 2020-05-29 11:56 UTC
# Other bugs

#### What were you trying to do?

Trying to shutdown the bot makes it speak out an error in console.

#### What were you expecting to happen?

No errors in shutdown? not sure what to put here. xD

#### What actually happened?

I spoke with Draper about this on the Red Discord Server.
This is what showed.

![image](https://user-images.githubusercontent.com/6032823/83257494-ca64a480-a1b4-11ea-8a45-8a79fba17077.png)
![image](https://user-images.githubusercontent.com/6032823/83257507-d2244900-a1b4-11ea-9bc7-7ed6aed2c1b1.png)
Related conversation in #support: https://ptb.discordapp.com/channels/133049272517001216/387398816317440000/715888540008841258 

#### How can we reproduce this issue?

Not sure if others experience this, but what I do is I shutdown the bot and it gives that error.

However I do have to say I've debugged the issue together with Draper's help. I've done the `[p]shutdown` command with every single cog including custom cogs, and it stopped happening as soon as I unloaded the Streams cog, I have double checked whether it was the Streams cog by just loading Streams cog alone and shutdown the bot and it in fact was the Streams cog.

EDIT: Just to clarify, I have done this with every cog (loaded 1 by 1) and only the Streams cog gives that error for me.

I hope this is enough information, if you need anything else let me know, and I'll do what I can.

**Comment by mikeshardmind** [comment] 2020-05-29 12:13
Duplicate of #3560 , related to #3566 and [python BPO-39232](https://bugs.python.org/issue39232), Not a streams issue.

**Comment by Robert606** [comment] 2020-05-30 10:54
it only happens with the Stream cog, so i thought it was a Streams cog issue. Hence why i reported it as such.

**Comment by mikeshardmind** [comment] 2020-05-30 10:57
Oh sure. Sorry, if I came across a bit brusque there, this isn't an easy issue to track down let alone solve and how the issue presents is still important, just tacking on info based on what was known.

**Comment by Kowlin** [comment] 2020-05-30 11:00
Closing as a duplicate of #3560

**Closed as completed** 2020-05-30 11:00 UTC
Labels: Type: Bug, Status: Needs Triage, Category: Cogs - Streams
