### ISSUE TITLE
Translations are not respect new lines properly

### ISSUE THREAD

**Issue by PredaaA** [Cog-Creators/Red-DiscordBot#2435] opened 2019-02-08 18:52 UTC
# Other bugs
### What were you trying to do?

When translating a cogs  `.po` file to use in another language, new lines are not respected properly.
See images below.

### What were you expecting to happen?
I want to have the same line formatting that are on this image when translating a cog.
![2019-02-08 16_58_19-window](https://user-images.githubusercontent.com/46051820/52497804-4d847480-2bd7-11e9-9162-03a0c6f7e3bd.png)

### What actually happened?
With just one `\n` in fields in the  `.po` file there's not line break
![2019-02-08 16_58_09-window](https://user-images.githubusercontent.com/46051820/52497928-aa802a80-2bd7-11e9-91ec-d7db9b09ccb2.png)

Then with two `\n` in fields in the  `.po` file it works but add a second line break that it's unwanted.
![2019-02-08 18_36_55-window](https://user-images.githubusercontent.com/46051820/52498027-ec10d580-2bd7-11e9-8534-9d06c045b69c.png)

And there's the a screenshot of the `.po` translation file and [link of the po file](https://hastebin.com/okaroyamiz.nginx) for this part
![2019-02-08 17_01_19-window](https://user-images.githubusercontent.com/46051820/52498715-d3092400-2bd9-11e9-8180-7d445534517b.png)

**Comment by entchen66** [comment] 2019-02-11 22:04
The same problem I have noticed in the repo list and in the cog list:
![grafik](https://user-images.githubusercontent.com/1564726/52596763-68621d80-2e51-11e9-8a52-fdd69b531ca0.png)
![grafik](https://user-images.githubusercontent.com/1564726/52596778-731cb280-2e51-11e9-987e-f2e115712199.png)

**Comment by Fozar** [comment] 2019-02-13 15:05
[Same problem](https://github.com/Cog-Creators/Red-DiscordBot/issues/2408)

**Comment by Tobotimus** [comment] 2019-02-19 21:28
I'm gonna mark this as a duplicate of #2408, and use that to track this general issue with translations not being loaded or rendered properly.

**Closed as completed by Tobotimus** 2019-02-19 21:28 UTC
Labels: Type: Bug, Closed: Duplicate, Category: Core - i18n
