### ISSUE TITLE
Warnings Cog [p]warnings command for Mods

### ISSUE THREAD

**Issue by Dav-Git** [Cog-Creators/Red-DiscordBot#3086] opened 2019-10-26 09:27 UTC
# Command bugs

#### Command name

[p]warnings

#### What cog is this command from?

Warnings

#### What were you expecting to happen?

It would be good to allow people with the modrole to check the warnings for a user. Maybe as a togglable option? Or based on permissions handled by the Permissions Cog. If a user can run the [p]warnings command, that user should also be able to expect full functionality. If a User should not be able to run the [p]warnings command, just disallow it using the Permissions cog.

#### What actually happened?

Only admins can see the results of [p]warnings.

#### How can we reproduce this issue?

1.Enable warnings Cog
2.Set a modrole and adminrole
3.Set the permissions to allow the use of the Warnings Cog for the role you used as modrole
4.Warn someone
5.Try to use [p]warnings <User you just warned> with a user that is just a member of the modrole

**Comment by mikeshardmind** [comment] 2019-10-26 09:36
Red's permission model would require these two separate behaviors to be split into separate commands. A command anyone could run by default to view their own warnings, and a command which used a normal permissions override-able check (at the same admin default level) to view others.

**Comment by Vexed01** [comment] 2019-10-26 09:37
Also with default perms, only admins can warn people. Would this be changed as well so mods can warn people (which makes sense)?

**Comment by mikeshardmind** [comment] 2019-10-26 09:43
I don't see a reason to make the default more permissive as a part of this. Using permissions, people can make it less restrictive, and warnings (Depending on how configured) could allow a mod to take an action against a user they normally would be incapable of by spamming warns.

While this *is* more an issue of "how much do you trust your mods", the defaults shouldn't require trusting them as much as an admin, and can be handled with permissions.

**Comment by mikeshardmind** [comment] 2019-10-26 11:33
Duplicate of #2900

**Closed as completed by mikeshardmind** 2019-10-26 11:33 UTC
Labels: Status: Accepted
