### ISSUE TITLE
error while downloading requirements, please help.

### ISSUE THREAD

**Issue by SCRCE** [Cog-Creators/Red-DiscordBot#1993] opened 2018-08-09 06:45 UTC
==========================
Red Discord Bot - Launcher
==========================

Main requirements:

1. Install basic + audio requirements (recommended)
2. Install basic requirements

ffmpeg (required for audio):
3. Install ffmpeg 32bit
4. Install ffmpeg 64bit (recommended on Windows 64bit)

0. Go back
> 1
Collecting pip (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Collecting discord.py[voice] from git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning git://github.com/Rapptz/discord.py.git to c:\users\scrce\appdata\local\temp\pip-install-700lwsri\discord.py
Collecting youtube_dl (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/c2/3b/17a27fecceb768ebec9e0d650fb764d47a5810b6840ea77177f128e2f0a8/youtube_dl-2018.8.4-py2.py3-none-any.whl
Collecting imgurpython (from -r requirements.txt (line 4))
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]->-r requirements.txt (line 2))
Collecting websockets<4.0,>=3.1 (from discord.py[voice]->-r requirements.txt (line 2))
Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/dd/99/bc86d40c88c1e1c6c9338d5afa91e3126d1ae28ad1bdfac79ab5b01803df/PyNaCl-1.0.1.tar.gz
Collecting requests (from imgurpython->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/96/0f/e6357458c87fb4ed8f3df215773f3caad40968f10e05552cbd8bd28415e4/async_timeout-3.0.0-py3-none-any.whl
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/2d/9e/9d84a78d4ea3d0fa94f6d0e4bcd88406709312949f48f3853f26f8f52ebe/cffi-1.11.5-cp37-cp37m-win32.whl
Collecting idna<2.8,>=2.5 (from requests->imgurpython->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->imgurpython->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->imgurpython->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice]->-r requirements.txt (line 2))
Building wheels for collected packages: discord.py, PyNaCl
  Running setup.py bdist_wheel for discord.py ... done
  Stored in directory: C:\Users\SCRCE\AppData\Local\Temp\pip-ephem-wheel-cache-amylf3w1\wheels\3c\fa\9f\d59bd15d1b416560f49b9676fc7a5bc7d2d16a9ab032e55c05
  Running setup.py bdist_wheel for PyNaCl ... error
  Complete output from command C:\Users\SCRCE\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SCRCE\\AppData\\Local\\Temp\\pip-install-700lwsri\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\SCRCE\AppData\Local\Temp\pip-wheel-9eaolf6j --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\nacl
  copying src\nacl\encoding.py -> build\lib.win32-3.7\nacl
  copying src\nacl\exceptions.py -> build\lib.win32-3.7\nacl
  copying src\nacl\hash.py -> build\lib.win32-3.7\nacl
  copying src\nacl\public.py -> build\lib.win32-3.7\nacl
  copying src\nacl\secret.py -> build\lib.win32-3.7\nacl
  copying src\nacl\signing.py -> build\lib.win32-3.7\nacl
  copying src\nacl\utils.py -> build\lib.win32-3.7\nacl
  copying src\nacl\__init__.py -> build\lib.win32-3.7\nacl
  creating build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\crypto_box.py -> build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\crypto_hash.py -> build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\crypto_sign.py -> build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\randombytes.py -> build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\sodium_core.py -> build\lib.win32-3.7\nacl\bindings
  copying src\nacl\bindings\__init__.py -> build\lib.win32-3.7\nacl\bindings
  running build_clib
  error: [WinError 193] %1 is not a valid Win32 application

  ----------------------------------------
  Failed building wheel for PyNaCl
  Running setup.py clean for PyNaCl
Successfully built discord.py
Failed to build PyNaCl
Installing collected packages: pip, async-timeout, multidict, chardet, aiohttp, websockets, six, pycparser, cffi, PyNaCl, discord.py, youtube-dl, idna, certifi, urllib3, requests, imgurpython
  Running setup.py install for PyNaCl ... error
    Complete output from command C:\Users\SCRCE\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SCRCE\\AppData\\Local\\Temp\\pip-install-700lwsri\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SCRCE\AppData\Local\Temp\pip-record-8jd6b_po\install-record.txt --single-version-externally-managed --compile --home=C:\Users\SCRCE\AppData\Local\Temp\pip-target-pf49qgu5:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\nacl
    copying src\nacl\encoding.py -> build\lib.win32-3.7\nacl
    copying src\nacl\exceptions.py -> build\lib.win32-3.7\nacl
    copying src\nacl\hash.py -> build\lib.win32-3.7\nacl
    copying src\nacl\public.py -> build\lib.win32-3.7\nacl
    copying src\nacl\secret.py -> build\lib.win32-3.7\nacl
    copying src\nacl\signing.py -> build\lib.win32-3.7\nacl
    copying src\nacl\utils.py -> build\lib.win32-3.7\nacl
    copying src\nacl\__init__.py -> build\lib.win32-3.7\nacl
    creating build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_hash.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\randombytes.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\sodium_core.py -> build\lib.win32-3.7\nacl\bindings
    copying src\nacl\bindings\__init__.py -> build\lib.win32-3.7\nacl\bindings
    running build_clib
    error: [WinError 193] %1 is not a valid Win32 application

    ----------------------------------------
Command "C:\Users\SCRCE\AppData\Local\Programs\Python\Python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SCRCE\\AppData\\Local\\Temp\\pip-install-700lwsri\\PyNaCl\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SCRCE\AppData\Local\Temp\pip-record-8jd6b_po\install-record.txt --single-version-externally-managed --compile --home=C:\Users\SCRCE\AppData\Local\Temp\pip-target-pf49qgu5" failed with error code 1 in C:\Users\SCRCE\AppData\Local\Temp\pip-install-700lwsri\PyNaCl\

An error occurred and the requirements setup might not be completed. Consult the docs.

Press enter to continue.

**Comment by Tobotimus** [comment] 2018-08-09 06:58
As the traceback suggests, `Consult the docs`, and as all of our issue templates say, please search other issues before posting a new one. Duplicate of #1939, you can find your solution there

**Closed as completed by Tobotimus** 2018-08-09 06:58 UTC
Labels: Closed: Duplicate, Closed: User Error
