### ISSUE TITLE
[Trivia] `[p]triviaset override` does nothing

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#3582] opened 2020-02-20 15:56 UTC
I'm not entirely sure how it was supposed to work or if we still want it, but I noticed there is a setting for allowing trivia lists to override settings but it's not implemented.

**Comment by aikaterna** [comment] 2020-06-16 17:35
I did some investigating on this and the relevant information is from Oct 2017 from the discussion of rewriting Trivia for v3. This was intended to be added to trivia via a feature-ideas request so that users could theoretically add a key named CONFIG in their trivia that would have trivia-list based overrides. I did not find any other discussion on this via any GH issues or PRs or anyone continuing this work after the initial Trivia rewrite, nor have I seen requests for this feature while working in support over the last couple of years. At this point I would wonder if we could just drop it, but by bringing it up again with this comment we may find someone interested in continuing this work. IMO the setting and the display for it should be removed currently as it does nothing, as you mentioned.

**Comment by aikaterna** [comment] 2020-06-16 18:14
Looks like there's some code involved in Trivia that actually handles this: https://github.com/Cog-Creators/Red-DiscordBot/blob/e59d52bae452259dca73deef81f5dd9c103086ec/redbot/cogs/trivia/trivia.py#L311 and in my testing it appeared to work as intended.

At this point (and after discussing with Jack, so I'm not making a unilateral decision here) I will be closing this issue and opening another issue asking for documenting the CONFIG key & also asking for some sort of display under triviaset custom that could show users if a trivia file has specific overrides.

**Closed as completed by aikaterna** 2020-06-16 18:14 UTC
Labels: Closed: Invalid, Type: Informational, Category: Cogs - Trivia
