### ISSUE TITLE
[V3] Audio: disconnect

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#2044] opened 2018-08-23 14:44 UTC
# Command bugs

#### Command name

disconnect

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Allow anyone to disconnect the bot once the music stops.

#### What actually happened?

The boy say's that "There are other people listening to music" 

#### How can we reproduce this issue?

![discord_2018-08-23_15-43-42](https://user-images.githubusercontent.com/31554168/44532612-6497de80-a6eb-11e8-880d-748c84e74510.png)

**Comment by aikaterna** [comment] 2018-08-23 15:07
We spoke in the v3 support channel on the support server, but this is intended. If a pleb is in a channel with other people, we don't want to allow them to disconnect whenever they feel like, stopping the music for everyone else. However if they are alone in the channel, they can use disconnect without that message. Mods like Red admins, mods, bot owner, server owner, etc, will not get this message when trying to use disconnect with other people in the channel.

**Comment by Tobotimus** [comment] 2018-08-24 00:32
Marking as resolved since this is intended behaviour.

**Closed as completed by Tobotimus** 2018-08-24 00:32 UTC
Labels: Type: Question
