### ISSUE TITLE
Automated error

### ISSUE THREAD

**Issue by Kio-td** [Cog-Creators/Red-DiscordBot#1326] opened 2018-02-20 05:30 UTC
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
Automated Mod error
### Expected behavior
[No error, no traceback]
### Actual behavior
Prints the following:
```
[20/02/2018 00:28] ERROR events on_error 138: Exception in message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 223, in _run_event
    yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/mod/mod.py", line 1246, in on_message
    mod_or_superior = await is_mod_or_superior(self.bot, obj=author)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/utils/mod.py", line 134, in is_mod_or_superior
    server = obj.guild
AttributeError: 'User' object has no attribute 'guild'
```

### Steps to reproduce
--Unknown.--

**Comment by Kowlin** [comment] 2018-02-20 05:37
Duplicate of #1202

**Closed as completed by Kowlin** 2018-02-20 05:37 UTC
Labels: Closed: Duplicate

**Comment by Tobotimus** [comment] 2018-02-20 06:11
On re-inspection this issue wasn't *exactly* a duplicate as it's more to do with the usage of `is_mod_or_superior` rather than its implementation (as is the emphasis in #1202), so I've transferred some of this issue's arguments over to #1202.

Thanks for submitting this issue :)
